<hr style="
    border: 0;
    height: 2px;
    background-color:#17B978;
    width:70%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">


<div style="text-align:center;">

<h style="color:#17B978; font-size:48px; margin-bottom:10px;">
  🐍  <b>Sprint 12</b>  🌐</h><br><br>
  <h2 style="color:#6F0000; font-size:42px; margin-top:0;">
    APIs REST
  </h2>

</div>
<hr style="
    border: 0;
    height: 2px;
    background-color:#17B978;
    width:70%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

In [248]:
# Import library

import requests
import pandas as pd

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:65%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">


<div style="text-align:center;">

<h2 style="color:#17B978">Description :</h2>

<p style="color:#777777;">
I will apply what i have learned about REST APIs, HTTP methods, and status codes by using public APIs<br> to retrieve data, filter it, and finally store it in a pandas DataFrame.
</p>



<p style="color:#F7FF56; font-style:italic;">
For this Sprint, all documentation and code will be written entirely in English to ensure consistency and technical clarity.<br>
Database of level 3 is in Catalan.
</p>

</div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:65%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<hr style="
    border: 0;
    height: 2px;
    background-color:#17B978;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">


<div style="text-align:center;">

<h style="color:#17B978; font-size:32px; margin-bottom:10px;">
 <b2>LEVEL 1</b2></h><br><br>

<h style="color:#6F0000; font-size:24px; margin-bottom:10px;">
 <b2>Resource:</b2></h><br>
 <br>
<a href="https://jsonplaceholder.typicode.com/" style="color:#F7FF56;">
   🔗 jsonplaceholder 🔗
</a>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 1 :</h4>

<p style="color:#777777;">
Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:
<p style="color:#777777;">
- Llista de publicacions (/posts)<br>
- Llista d’usuaris (/users)<br>
- Llista de tasques (/todos)<br>
</p>

In [249]:
# Posts

posts = requests.get(r"https://jsonplaceholder.typicode.com/posts")
print(posts.text)

[
  {
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
  },
  {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
  },
  {
    "userId": 1,
    "id": 3,
    "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
  },
  {
    "userId": 1,
    "id": 4,
    "title": "eum et est occaecati",
    "body": "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit"
  },
  {
    "userId": 1,
    "id": 5,
    "title": "nesciunt quas odio",
    "body": "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque"
  },
  {
    "userId": 1,
    "id": 6,
    "title": "dolorem eum magni eos aperiam quia",
    "body": "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae"
  },
  {
    "userId": 1,
    "id": 7,
    "title": "magnam facilis autem",
    "body": "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas"
  },
  {
    "userId": 1,
    "id": 8,
    "title": "dolorem dolore est ipsam",
    "body": "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae"
  },
  {
    "userId": 1,
    "id": 9,
    "title": "nesciunt iure omnis dolorem tempora et accusantium",
    "body": "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas"
  },
  {
    "userId": 1,
    "id": 10,
    "title": "optio molestias id quia eum",
    "body": "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error"
  },
  {
    "userId": 2,
    "id": 11,
    "title": "et ea vero quia laudantium autem",
    "body": "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi"
  },
  {
    "userId": 2,
    "id": 12,
    "title": "in quibusdam tempore odit est dolorem",
    "body": "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio"
  },
  {
    "userId": 2,
    "id": 13,
    "title": "dolorum ut in voluptas mollitia et saepe quo animi",
    "body": "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam"
  },
  {
    "userId": 2,
    "id": 14,
    "title": "voluptatem eligendi optio",
    "body": "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum"
  },
  {
    "userId": 2,
    "id": 15,
    "title": "eveniet quod temporibus",
    "body": "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae"
  },
  {
    "userId": 2,
    "id": 16,
    "title": "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio",
    "body": "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta"
  },
  {
    "userId": 2,
    "id": 17,
    "title": "fugit voluptas sed molestias voluptatem provident",
    "body": "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo"
  },
  {
    "userId": 2,
    "id": 18,
    "title": "voluptate et itaque vero tempora molestiae",
    "body": "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam"
  },
  {
    "userId": 2,
    "id": 19,
    "title": "adipisci placeat illum aut reiciendis qui",
    "body": "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas"
  },
  {
    "userId": 2,
    "id": 20,
    "title": "doloribus ad provident suscipit at",
    "body": "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo"
  },
  {
    "userId": 3,
    "id": 21,
    "title": "asperiores ea ipsam voluptatibus modi minima quia sint",
    "body": "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt"
  },
  {
    "userId": 3,
    "id": 22,
    "title": "dolor sint quo a velit explicabo quia nam",
    "body": "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse"
  },
  {
    "userId": 3,
    "id": 23,
    "title": "maxime id vitae nihil numquam",
    "body": "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis"
  },
  {
    "userId": 3,
    "id": 24,
    "title": "autem hic labore sunt dolores incidunt",
    "body": "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt"
  },
  {
    "userId": 3,
    "id": 25,
    "title": "rem alias distinctio quo quis",
    "body": "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio"
  },
  {
    "userId": 3,
    "id": 26,
    "title": "est et quae odit qui non",
    "body": "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero"
  },
  {
    "userId": 3,
    "id": 27,
    "title": "quasi id et eos tenetur aut quo autem",
    "body": "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur"
  },
  {
    "userId": 3,
    "id": 28,
    "title": "delectus ullam et corporis nulla voluptas sequi",
    "body": "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum"
  },
  {
    "userId": 3,
    "id": 29,
    "title": "iusto eius quod necessitatibus culpa ea",
    "body": "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores"
  },
  {
    "userId": 3,
    "id": 30,
    "title": "a quo magni similique perferendis",
    "body": "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia"
  },
  {
    "userId": 4,
    "id": 31,
    "title": "ullam ut quidem id aut vel consequuntur",
    "body": "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae"
  },
  {
    "userId": 4,
    "id": 32,
    "title": "doloremque illum aliquid sunt",
    "body": "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime"
  },
  {
    "userId": 4,
    "id": 33,
    "title": "qui explicabo molestiae dolorem",
    "body": "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod"
  },
  {
    "userId": 4,
    "id": 34,
    "title": "magnam ut rerum iure",
    "body": "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis"
  },
  {
    "userId": 4,
    "id": 35,
    "title": "id nihil consequatur molestias animi provident",
    "body": "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit"
  },
  {
    "userId": 4,
    "id": 36,
    "title": "fuga nam accusamus voluptas reiciendis itaque",
    "body": "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore"
  },
  {
    "userId": 4,
    "id": 37,
    "title": "provident vel ut sit ratione est",
    "body": "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui"
  },
  {
    "userId": 4,
    "id": 38,
    "title": "explicabo et eos deleniti nostrum ab id repellendus",
    "body": "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure"
  },
  {
    "userId": 4,
    "id": 39,
    "title": "eos dolorem iste accusantium est eaque quam",
    "body": "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex"
  },
  {
    "userId": 4,
    "id": 40,
    "title": "enim quo cumque",
    "body": "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam"
  },
  {
    "userId": 5,
    "id": 41,
    "title": "non est facere",
    "body": "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe"
  },
  {
    "userId": 5,
    "id": 42,
    "title": "commodi ullam sint et excepturi error explicabo praesentium voluptas",
    "body": "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut"
  },
  {
    "userId": 5,
    "id": 43,
    "title": "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis",
    "body": "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis"
  },
  {
    "userId": 5,
    "id": 44,
    "title": "optio dolor molestias sit",
    "body": "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae"
  },
  {
    "userId": 5,
    "id": 45,
    "title": "ut numquam possimus omnis eius suscipit laudantium iure",
    "body": "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem"
  },
  {
    "userId": 5,
    "id": 46,
    "title": "aut quo modi neque nostrum ducimus",
    "body": "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid"
  },
  {
    "userId": 5,
    "id": 47,
    "title": "quibusdam cumque rem aut deserunt",
    "body": "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate"
  },
  {
    "userId": 5,
    "id": 48,
    "title": "ut voluptatem illum ea doloribus itaque eos",
    "body": "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit"
  },
  {
    "userId": 5,
    "id": 49,
    "title": "laborum non sunt aut ut assumenda perspiciatis voluptas",
    "body": "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut"
  },
  {
    "userId": 5,
    "id": 50,
    "title": "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem",
    "body": "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur"
  },
  {
    "userId": 6,
    "id": 51,
    "title": "soluta aliquam aperiam consequatur illo quis voluptas",
    "body": "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem"
  },
  {
    "userId": 6,
    "id": 52,
    "title": "qui enim et consequuntur quia animi quis voluptate quibusdam",
    "body": "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum"
  },
  {
    "userId": 6,
    "id": 53,
    "title": "ut quo aut ducimus alias",
    "body": "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique"
  },
  {
    "userId": 6,
    "id": 54,
    "title": "sit asperiores ipsam eveniet odio non quia",
    "body": "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia"
  },
  {
    "userId": 6,
    "id": 55,
    "title": "sit vel voluptatem et non libero",
    "body": "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit"
  },
  {
    "userId": 6,
    "id": 56,
    "title": "qui et at rerum necessitatibus",
    "body": "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi"
  },
  {
    "userId": 6,
    "id": 57,
    "title": "sed ab est est",
    "body": "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est"
  },
  {
    "userId": 6,
    "id": 58,
    "title": "voluptatum itaque dolores nisi et quasi",
    "body": "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam"
  },
  {
    "userId": 6,
    "id": 59,
    "title": "qui commodi dolor at maiores et quis id accusantium",
    "body": "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt"
  },
  {
    "userId": 6,
    "id": 60,
    "title": "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere",
    "body": "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis"
  },
  {
    "userId": 7,
    "id": 61,
    "title": "voluptatem doloribus consectetur est ut ducimus",
    "body": "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit"
  },
  {
    "userId": 7,
    "id": 62,
    "title": "beatae enim quia vel",
    "body": "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio"
  },
  {
    "userId": 7,
    "id": 63,
    "title": "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit",
    "body": "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta"
  },
  {
    "userId": 7,
    "id": 64,
    "title": "et fugit quas eum in in aperiam quod",
    "body": "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui"
  },
  {
    "userId": 7,
    "id": 65,
    "title": "consequatur id enim sunt et et",
    "body": "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur"
  },
  {
    "userId": 7,
    "id": 66,
    "title": "repudiandae ea animi iusto",
    "body": "officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe"
  },
  {
    "userId": 7,
    "id": 67,
    "title": "aliquid eos sed fuga est maxime repellendus",
    "body": "reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae"
  },
  {
    "userId": 7,
    "id": 68,
    "title": "odio quis facere architecto reiciendis optio",
    "body": "magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit"
  },
  {
    "userId": 7,
    "id": 69,
    "title": "fugiat quod pariatur odit minima",
    "body": "officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a"
  },
  {
    "userId": 7,
    "id": 70,
    "title": "voluptatem laborum magni",
    "body": "sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore"
  },
  {
    "userId": 8,
    "id": 71,
    "title": "et iusto veniam et illum aut fuga",
    "body": "occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis"
  },
  {
    "userId": 8,
    "id": 72,
    "title": "sint hic doloribus consequatur eos non id",
    "body": "quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit"
  },
  {
    "userId": 8,
    "id": 73,
    "title": "consequuntur deleniti eos quia temporibus ab aliquid at",

In [250]:
# Users

users = requests.get(r"https://jsonplaceholder.typicode.com/users")
print(users.text)

[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net",
    "company": {
      "name": "Deckow-Crist",
      "catchPhrase": "Proactive didactic contingency",
      "bs": "synergize scalable supply-chains"
    }
  },
  {
    "id": 3,
    "name": "Clementine Bauch",
    "username": "Samantha",
    "email": "Nathan@yesenia.net",
    "address": {
      "street": "Douglas Extension",
      "suite": "Suite 847",
      "city": "McKenziehaven",
      "zipcode": "59590-4157",
      "geo": {
        "lat": "-68.6102",
        "lng": "-47.0653"
      }
    },
    "phone": "1-463-123-4447",
    "website": "ramiro.info",
    "company": {
      "name": "Romaguera-Jacobson",
      "catchPhrase": "Face to face bifurcated interface",
      "bs": "e-enable strategic applications"
    }
  },
  {
    "id": 4,
    "name": "Patricia Lebsack",
    "username": "Karianne",
    "email": "Julianne.OConner@kory.org",
    "address": {
      "street": "Hoeger Mall",
      "suite": "Apt. 692",
      "city": "South Elvis",
      "zipcode": "53919-4257",
      "geo": {
        "lat": "29.4572",
        "lng": "-164.2990"
      }
    },
    "phone": "493-170-9623 x156",
    "website": "kale.biz",
    "company": {
      "name": "Robel-Corkery",
      "catchPhrase": "Multi-tiered zero tolerance productivity",
      "bs": "transition cutting-edge web services"
    }
  },
  {
    "id": 5,
    "name": "Chelsey Dietrich",
    "username": "Kamren",
    "email": "Lucio_Hettinger@annie.ca",
    "address": {
      "street": "Skiles Walks",
      "suite": "Suite 351",
      "city": "Roscoeview",
      "zipcode": "33263",
      "geo": {
        "lat": "-31.8129",
        "lng": "62.5342"
      }
    },
    "phone": "(254)954-1289",
    "website": "demarco.info",
    "company": {
      "name": "Keebler LLC",
      "catchPhrase": "User-centric fault-tolerant solution",
      "bs": "revolutionize end-to-end systems"
    }
  },
  {
    "id": 6,
    "name": "Mrs. Dennis Schulist",
    "username": "Leopoldo_Corkery",
    "email": "Karley_Dach@jasper.info",
    "address": {
      "street": "Norberto Crossing",
      "suite": "Apt. 950",
      "city": "South Christy",
      "zipcode": "23505-1337",
      "geo": {
        "lat": "-71.4197",
        "lng": "71.7478"
      }
    },
    "phone": "1-477-935-8478 x6430",
    "website": "ola.org",
    "company": {
      "name": "Considine-Lockman",
      "catchPhrase": "Synchronised bottom-line interface",
      "bs": "e-enable innovative applications"
    }
  },
  {
    "id": 7,
    "name": "Kurtis Weissnat",
    "username": "Elwyn.Skiles",
    "email": "Telly.Hoeger@billy.biz",
    "address": {
      "street": "Rex Trail",
      "suite": "Suite 280",
      "city": "Howemouth",
      "zipcode": "58804-1099",
      "geo": {
        "lat": "24.8918",
        "lng": "21.8984"
      }
    },
    "phone": "210.067.6132",
    "website": "elvis.io",
    "company": {
      "name": "Johns Group",
      "catchPhrase": "Configurable multimedia task-force",
      "bs": "generate enterprise e-tailers"
    }
  },
  {
    "id": 8,
    "name": "Nicholas Runolfsdottir V",
    "username": "Maxime_Nienow",
    "email": "Sherwood@rosamond.me",
    "address": {
      "street": "Ellsworth Summit",
      "suite": "Suite 729",
      "city": "Aliyaview",
      "zipcode": "45169",
      "geo": {
        "lat": "-14.3990",
        "lng": "-120.7677"
      }
    },
    "phone": "586.493.6943 x140",
    "website": "jacynthe.com",
    "company": {
      "name": "Abernathy Group",
      "catchPhrase": "Implemented secondary concept",
      "bs": "e-enable extensible e-tailers"
    }
  },
  {
    "id": 9,
    "name": "Glenna Reichert",
    "username": "Delphine",
    "email": "Chaim_McDermott@dana.io",
    "address": {
      "street": "Dayna Park",
      "suite": "Suite 449",
      "city": "Bartholomebury",
      "zipcode": "76495-3109",
      "geo": {
        "lat": "24.6463",
        "lng": "-168.8889"
      }
    },
    "phone": "(775)976-6794 x41206",
    "website": "conrad.com",
    "company": {
      "name": "Yost and Sons",
      "catchPhrase": "Switchable contextually-based project",
      "bs": "aggregate real-time technologies"
    }
  },
  {
    "id": 10,
    "name": "Clementina DuBuque",
    "username": "Moriah.Stanton",
    "email": "Rey.Padberg@karina.biz",
    "address": {
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "zipcode": "31428-2261",
      "geo": {
        "lat": "-38.2386",
        "lng": "57.2232"
      }
    },
    "phone": "024-648-3804",
    "website": "ambrose.net",
    "company": {
      "name": "Hoeger LLC",
      "catchPhrase": "Centralized empowering task-force",
      "bs": "target end-to-end models"
    }
  }
]

In [251]:
# All

todos = requests.get(r"https://jsonplaceholder.typicode.com/todos")
print(todos.text)

[
  {
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
  },
  {
    "userId": 1,
    "id": 2,
    "title": "quis ut nam facilis et officia qui",
    "completed": false
  },
  {
    "userId": 1,
    "id": 3,
    "title": "fugiat veniam minus",
    "completed": false
  },
  {
    "userId": 1,
    "id": 4,
    "title": "et porro tempora",
    "completed": true
  },
  {
    "userId": 1,
    "id": 5,
    "title": "laboriosam mollitia et enim quasi adipisci quia provident illum",
    "completed": false
  },
  {
    "userId": 1,
    "id": 6,
    "title": "qui ullam ratione quibusdam voluptatem quia omnis",
    "completed": false
  },
  {
    "userId": 1,
    "id": 7,
    "title": "illo expedita consequatur quia in",
    "completed": false
  },
  {
    "userId": 1,
    "id": 8,
    "title": "quo adipisci enim quam ut ab",
    "completed": true
  },
  {
    "userId": 1,
    "id": 9,
    "title": "molestiae perspiciatis ipsa",
    "completed": false
  },
  {
    "userId": 1,
    "id": 10,
    "title": "illo est ratione doloremque quia maiores aut",
    "completed": true
  },
  {
    "userId": 1,
    "id": 11,
    "title": "vero rerum temporibus dolor",
    "completed": true
  },
  {
    "userId": 1,
    "id": 12,
    "title": "ipsa repellendus fugit nisi",
    "completed": true
  },
  {
    "userId": 1,
    "id": 13,
    "title": "et doloremque nulla",
    "completed": false
  },
  {
    "userId": 1,
    "id": 14,
    "title": "repellendus sunt dolores architecto voluptatum",
    "completed": true
  },
  {
    "userId": 1,
    "id": 15,
    "title": "ab voluptatum amet voluptas",
    "completed": true
  },
  {
    "userId": 1,
    "id": 16,
    "title": "accusamus eos facilis sint et aut voluptatem",
    "completed": true
  },
  {
    "userId": 1,
    "id": 17,
    "title": "quo laboriosam deleniti aut qui",
    "completed": true
  },
  {
    "userId": 1,
    "id": 18,
    "title": "dolorum est consequatur ea mollitia in culpa",
    "completed": false
  },
  {
    "userId": 1,
    "id": 19,
    "title": "molestiae ipsa aut voluptatibus pariatur dolor nihil",
    "completed": true
  },
  {
    "userId": 1,
    "id": 20,
    "title": "ullam nobis libero sapiente ad optio sint",
    "completed": true
  },
  {
    "userId": 2,
    "id": 21,
    "title": "suscipit repellat esse quibusdam voluptatem incidunt",
    "completed": false
  },
  {
    "userId": 2,
    "id": 22,
    "title": "distinctio vitae autem nihil ut molestias quo",
    "completed": true
  },
  {
    "userId": 2,
    "id": 23,
    "title": "et itaque necessitatibus maxime molestiae qui quas velit",
    "completed": false
  },
  {
    "userId": 2,
    "id": 24,
    "title": "adipisci non ad dicta qui amet quaerat doloribus ea",
    "completed": false
  },
  {
    "userId": 2,
    "id": 25,
    "title": "voluptas quo tenetur perspiciatis explicabo natus",
    "completed": true
  },
  {
    "userId": 2,
    "id": 26,
    "title": "aliquam aut quasi",
    "completed": true
  },
  {
    "userId": 2,
    "id": 27,
    "title": "veritatis pariatur delectus",
    "completed": true
  },
  {
    "userId": 2,
    "id": 28,
    "title": "nesciunt totam sit blanditiis sit",
    "completed": false
  },
  {
    "userId": 2,
    "id": 29,
    "title": "laborum aut in quam",
    "completed": false
  },
  {
    "userId": 2,
    "id": 30,
    "title": "nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis",
    "completed": true
  },
  {
    "userId": 2,
    "id": 31,
    "title": "repudiandae totam in est sint facere fuga",
    "completed": false
  },
  {
    "userId": 2,
    "id": 32,
    "title": "earum doloribus ea doloremque quis",
    "completed": false
  },
  {
    "userId": 2,
    "id": 33,
    "title": "sint sit aut vero",
    "completed": false
  },
  {
    "userId": 2,
    "id": 34,
    "title": "porro aut necessitatibus eaque distinctio",
    "completed": false
  },
  {
    "userId": 2,
    "id": 35,
    "title": "repellendus veritatis molestias dicta incidunt",
    "completed": true
  },
  {
    "userId": 2,
    "id": 36,
    "title": "excepturi deleniti adipisci voluptatem et neque optio illum ad",
    "completed": true
  },
  {
    "userId": 2,
    "id": 37,
    "title": "sunt cum tempora",
    "completed": false
  },
  {
    "userId": 2,
    "id": 38,
    "title": "totam quia non",
    "completed": false
  },
  {
    "userId": 2,
    "id": 39,
    "title": "doloremque quibusdam asperiores libero corrupti illum qui omnis",
    "completed": false
  },
  {
    "userId": 2,
    "id": 40,
    "title": "totam atque quo nesciunt",
    "completed": true
  },
  {
    "userId": 3,
    "id": 41,
    "title": "aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit",
    "completed": false
  },
  {
    "userId": 3,
    "id": 42,
    "title": "rerum perferendis error quia ut eveniet",
    "completed": false
  },
  {
    "userId": 3,
    "id": 43,
    "title": "tempore ut sint quis recusandae",
    "completed": true
  },
  {
    "userId": 3,
    "id": 44,
    "title": "cum debitis quis accusamus doloremque ipsa natus sapiente omnis",
    "completed": true
  },
  {
    "userId": 3,
    "id": 45,
    "title": "velit soluta adipisci molestias reiciendis harum",
    "completed": false
  },
  {
    "userId": 3,
    "id": 46,
    "title": "vel voluptatem repellat nihil placeat corporis",
    "completed": false
  },
  {
    "userId": 3,
    "id": 47,
    "title": "nam qui rerum fugiat accusamus",
    "completed": false
  },
  {
    "userId": 3,
    "id": 48,
    "title": "sit reprehenderit omnis quia",
    "completed": false
  },
  {
    "userId": 3,
    "id": 49,
    "title": "ut necessitatibus aut maiores debitis officia blanditiis velit et",
    "completed": false
  },
  {
    "userId": 3,
    "id": 50,
    "title": "cupiditate necessitatibus ullam aut quis dolor voluptate",
    "completed": true
  },
  {
    "userId": 3,
    "id": 51,
    "title": "distinctio exercitationem ab doloribus",
    "completed": false
  },
  {
    "userId": 3,
    "id": 52,
    "title": "nesciunt dolorum quis recusandae ad pariatur ratione",
    "completed": false
  },
  {
    "userId": 3,
    "id": 53,
    "title": "qui labore est occaecati recusandae aliquid quam",
    "completed": false
  },
  {
    "userId": 3,
    "id": 54,
    "title": "quis et est ut voluptate quam dolor",
    "completed": true
  },
  {
    "userId": 3,
    "id": 55,
    "title": "voluptatum omnis minima qui occaecati provident nulla voluptatem ratione",
    "completed": true
  },
  {
    "userId": 3,
    "id": 56,
    "title": "deleniti ea temporibus enim",
    "completed": true
  },
  {
    "userId": 3,
    "id": 57,
    "title": "pariatur et magnam ea doloribus similique voluptatem rerum quia",
    "completed": false
  },
  {
    "userId": 3,
    "id": 58,
    "title": "est dicta totam qui explicabo doloribus qui dignissimos",
    "completed": false
  },
  {
    "userId": 3,
    "id": 59,
    "title": "perspiciatis velit id laborum placeat iusto et aliquam odio",
    "completed": false
  },
  {
    "userId": 3,
    "id": 60,
    "title": "et sequi qui architecto ut adipisci",
    "completed": true
  },
  {
    "userId": 4,
    "id": 61,
    "title": "odit optio omnis qui sunt",
    "completed": true
  },
  {
    "userId": 4,
    "id": 62,
    "title": "et placeat et tempore aspernatur sint numquam",
    "completed": false
  },
  {
    "userId": 4,
    "id": 63,
    "title": "doloremque aut dolores quidem fuga qui nulla",
    "completed": true
  },
  {
    "userId": 4,
    "id": 64,
    "title": "voluptas consequatur qui ut quia magnam nemo esse",
    "completed": false
  },
  {
    "userId": 4,
    "id": 65,
    "title": "fugiat pariatur ratione ut asperiores necessitatibus magni",
    "completed": false
  },
  {
    "userId": 4,
    "id": 66,
    "title": "rerum eum molestias autem voluptatum sit optio",
    "completed": false
  },
  {
    "userId": 4,
    "id": 67,
    "title": "quia voluptatibus voluptatem quos similique maiores repellat",
    "completed": false
  },
  {
    "userId": 4,
    "id": 68,
    "title": "aut id perspiciatis voluptatem iusto",
    "completed": false
  },
  {
    "userId": 4,
    "id": 69,
    "title": "doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit",
    "completed": false
  },
  {
    "userId": 4,
    "id": 70,
    "title": "ut sequi accusantium et mollitia delectus sunt",
    "completed": false
  },
  {
    "userId": 4,
    "id": 71,
    "title": "aut velit saepe ullam",
    "completed": false
  },
  {
    "userId": 4,
    "id": 72,
    "title": "praesentium facilis facere quis harum voluptatibus voluptatem eum",
    "completed": false
  },
  {
    "userId": 4,
    "id": 73,
    "title": "sint amet quia totam corporis qui exercitationem commodi",
    "completed": true
  },
  {
    "userId": 4,
    "id": 74,
    "title": "expedita tempore nobis eveniet laborum maiores",
    "completed": false
  },
  {
    "userId": 4,
    "id": 75,
    "title": "occaecati adipisci est possimus totam",
    "completed": false
  },
  {
    "userId": 4,
    "id": 76,
    "title": "sequi dolorem sed",
    "completed": true
  },
  {
    "userId": 4,
    "id": 77,
    "title": "maiores aut nesciunt delectus exercitationem vel assumenda eligendi at",
    "completed": false
  },
  {
    "userId": 4,
    "id": 78,
    "title": "reiciendis est magnam amet nemo iste recusandae impedit quaerat",
    "completed": false
  },
  {
    "userId": 4,
    "id": 79,
    "title": "eum ipsa maxime ut",
    "completed": true
  },
  {
    "userId": 4,
    "id": 80,
    "title": "tempore molestias dolores rerum sequi voluptates ipsum consequatur",
    "completed": true
  },
  {
    "userId": 5,
    "id": 81,
    "title": "suscipit qui totam",
    "completed": true
  },
  {
    "userId": 5,
    "id": 82,
    "title": "voluptates eum voluptas et dicta",
    "completed": false
  },
  {
    "userId": 5,
    "id": 83,
    "title": "quidem at rerum quis ex aut sit quam",
    "completed": true
  },
  {
    "userId": 5,
    "id": 84,
    "title": "sunt veritatis ut voluptate",
    "completed": false
  },
  {
    "userId": 5,
    "id": 85,
    "title": "et quia ad iste a",
    "completed": true
  },
  {
    "userId": 5,
    "id": 86,
    "title": "incidunt ut saepe autem",
    "completed": true
  },
  {
    "userId": 5,
    "id": 87,
    "title": "laudantium quae eligendi consequatur quia et vero autem",
    "completed": true
  },
  {
    "userId": 5,
    "id": 88,
    "title": "vitae aut excepturi laboriosam sint aliquam et et accusantium",
    "completed": false
  },
  {
    "userId": 5,
    "id": 89,
    "title": "sequi ut omnis et",
    "completed": true
  },
  {
    "userId": 5,
    "id": 90,
    "title": "molestiae nisi accusantium tenetur dolorem et",
    "completed": true
  },
  {
    "userId": 5,
    "id": 91,
    "title": "nulla quis consequatur saepe qui id expedita",
    "completed": true
  },
  {
    "userId": 5,
    "id": 92,
    "title": "in omnis laboriosam",
    "completed": true
  },
  {
    "userId": 5,
    "id": 93,
    "title": "odio iure consequatur molestiae quibusdam necessitatibus quia sint",
    "completed": true
  },
  {
    "userId": 5,
    "id": 94,
    "title": "facilis modi saepe mollitia",
    "completed": false
  },
  {
    "userId": 5,
    "id": 95,
    "title": "vel nihil et molestiae iusto assumenda nemo quo ut",
    "completed": true
  },
  {
    "userId": 5,
    "id": 96,
    "title": "nobis suscipit ducimus enim asperiores voluptas",
    "completed": false
  },
  {
    "userId": 5,
    "id": 97,
    "title": "dolorum laboriosam eos qui iure aliquam",
    "completed": false
  },
  {
    "userId": 5,
    "id": 98,
    "title": "debitis accusantium ut quo facilis nihil quis sapiente necessitatibus",
    "completed": true
  },
  {
    "userId": 5,
    "id": 99,
    "title": "neque voluptates ratione",
    "completed": false
  },
  {
    "userId": 5,
    "id": 100,
    "title": "excepturi a et neque qui expedita vel voluptate",
    "completed": false
  },
  {
    "userId": 6,
    "id": 101,
    "title": "explicabo enim cumque porro aperiam occaecati minima",
    "completed": false
  },
  {
    "userId": 6,
    "id": 102,
    "title": "sed ab consequatur",
    "completed": false
  },
  {
    "userId": 6,
    "id": 103,
    "title": "non sunt delectus illo nulla tenetur enim omnis",
    "completed": false
  },
  {
    "userId": 6,
    "id": 104,
    "title": "excepturi non laudantium quo",
    "completed": false
  },
  {
    "userId": 6,
    "id": 105,
    "title": "totam quia dolorem et illum repellat voluptas optio",
    "completed": true
  },
  {
    "userId": 6,
    "id": 106,
    "title": "ad illo quis voluptatem temporibus",
    "completed": true
  },
  {
    "userId": 6,
    "id": 107,
    "title": "praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt",
    "completed": false
  },
  {
    "userId": 6,
    "id": 108,
    "title": "a eos eaque nihil et exercitationem incidunt delectus",
    "completed": true
  },
  {
    "userId": 6,
    "id": 109,
    "title": "autem temporibus harum quisquam in culpa",
    "completed": true
  },
  {
    "userId": 6,
    "id": 110,
    "title": "aut aut ea corporis",
    "completed": true
  },
  {
    "userId": 6,
    "id": 111,
    "title": "magni accusantium labore et id quis provident",
    "completed": false
  },
  {
    "userId": 6,
    "id": 112,
    "title": "consectetur impedit quisquam qui deserunt non rerum consequuntur eius",
    "completed": false
  },
  {
    "userId": 6,
    "id": 113,
    "title": "quia atque aliquam sunt impedit voluptatum rerum assumenda nisi",
    "completed": false
  },
  {
    "userId": 6,
    "id": 114,
    "title": "cupiditate quos possimus corporis quisquam exercitationem beatae",
    "completed": false
  },
  {
    "userId": 6,
    "id": 115,
    "title": "sed et ea eum",
    "completed": false
  },
  {
    "userId": 6,
    "id": 116,
    "title": "ipsa dolores vel facilis ut",
    "completed": true
  },
  {
    "userId": 6,
    "id": 117,
    "title": "sequi quae est et qui qui eveniet asperiores",
    "completed": false
  },
  {
    "userId": 6,
    "id": 118,
    "title": "quia modi consequatur vero fugiat",
    "completed": false
  },
  {
    "userId": 6,
    "id": 119,
    "title": "corporis ducimus ea perspiciatis iste",
    "completed": false
  },
  {
    "userId": 6,
    "id": 120,
    "title": "dolorem laboriosam vel voluptas et aliquam quasi",
    "completed": false
  },
  {
    "userId": 7,
    "id": 121,
    "title": "inventore aut nihil minima laudantium hic qui omnis",
    "completed": true
  },
  {
    "userId": 7,
    "id": 122,
    "title": "provident aut nobis culpa",
    "completed": true
  },
  {
    "userId": 7,
    "id": 123,
    "title": "esse et quis iste est earum aut impedit",
    "completed": false
  },
  {
    "userId": 7,
    "id": 124,
    "title": "qui consectetur id",
    "completed": false
  },
  {
    "userId": 7,
    "id": 125,
    "title": "aut quasi autem iste tempore illum possimus",
    "completed": false
  },
  {
    "userId": 7,
    "id": 126,
    "title": "ut asperiores perspiciatis veniam ipsum rerum saepe",
    "completed": true
  },
  {
    "userId": 7,
    "id": 127,
    "title": "voluptatem libero consectetur rerum ut",
    "completed": true
  },
  {
    "userId": 7,
    "id": 128,
    "title": "eius omnis est qui voluptatem autem",
    "completed": false
  },
  {
    "userId": 7,
    "id": 129,
    "title": "rerum culpa quis harum",
    "completed": false
  },
  {
    "userId": 7,
    "id": 130,
    "title": "nulla aliquid eveniet harum laborum libero alias ut unde",
    "completed": true
  },
  {
    "userId": 7,
    "id": 131,
    "title": "qui ea incidunt quis",
    "completed": false
  },
  {
    "userId": 7,
    "id": 132,
    "title": "qui molestiae voluptatibus velit iure harum quisquam",
    "completed": true
  },
  {
    "userId": 7,
    "id": 133,
    "title": "et labore eos enim rerum consequatur sunt",
    "completed": true
  },
  {
    "userId": 7,
    "id": 134,
    "title": "molestiae doloribus et laborum quod ea",
    "completed": false
  },
  {
    "userId": 7,
    "id": 135,
    "title": "facere ipsa nam eum voluptates reiciendis vero qui",
    "completed": false
  },
  {
    "userId": 7,
    "id": 136,
    "title": "asperiores illo tempora fuga sed ut quasi adipisci",
    "completed": false
  },
  {
    "userId": 7,
    "id": 137,
    "title": "qui sit non",
    "completed": false
  },
  {
    "userId": 7,
    "id": 138,
    "title": "placeat minima consequatur rem qui ut",
    "completed": true
  },
  {
    "userId": 7,
    "id": 139,
    "title": "consequatur doloribus id possimus voluptas a voluptatem",
    "completed": false
  },
  {
    "userId": 7,
    "id": 140,
    "title": "aut consectetur in blanditiis deserunt quia sed laboriosam",
    "completed": true
  },
  {
    "userId": 8,
    "id": 141,
    "title": "explicabo consectetur debitis voluptates quas quae culpa rerum non",
    "completed": true
  },
  {
    "userId": 8,
    "id": 142,
    "title": "maiores accusantium architecto necessitatibus reiciendis ea aut",
    "completed": true
  },
  {
    "userId": 8,
    "id": 143,
    "title": "eum non recusandae cupiditate animi",
    "completed": false
  },
  {
    "userId": 8,
    "id": 144,
    "title": "ut eum exercitationem sint",
    "completed": false
  },
  {
    "userId": 8,
    "id": 145,
    "title": "beatae qui ullam incidunt voluptatem non nisi aliquam",
    "completed": false
  },
  {
    "userId": 8,
    "id": 146,
    "title": "molestiae suscipit ratione nihil odio libero impedit vero totam",
    "completed": true
  },
  {
    "userId": 8,
    "id": 147,
    "title": "eum itaque quod reprehenderit et facilis dolor autem ut",
    "completed": true
  },
  {
    "userId": 8,
    "id": 148,
    "title": "esse quas et quo quasi exercitationem",
    "completed": false
  },
  {
    "userId": 8,
    "id": 149,
    "title": "animi voluptas quod perferendis est",
    "completed": false
  },
  {
    "userId": 8,
    "id": 150,
    "title": "eos amet tempore laudantium fugit a",
    "completed": false
  },
  {
    "userId": 8,
    "id": 151,
    "title": "accusamus adipisci dicta qui quo ea explicabo sed vero",
    "completed": true
  },
  {
    "userId": 8,
    "id": 152,
    "title": "odit eligendi recusandae doloremque cumque non",
    "completed": false
  },
  {
    "userId": 8,
    "id": 153,
    "title": "ea aperiam consequatur qui repellat eos",
    "completed": false
  },
  {
    "userId": 8,
    "id": 154,
    "title": "rerum non ex sapiente",
    "completed": true
  },
  {
    "userId": 8,
    "id": 155,
    "title": "voluptatem nobis consequatur et assumenda magnam",
    "completed": true
  },
  {
    "userId": 8,
    "id": 156,
    "title": "nam quia quia nulla repellat assumenda quibusdam sit nobis",
    "completed": true
  },
  {
    "userId": 8,
    "id": 157,
    "title": "dolorem veniam quisquam deserunt repellendus",
    "completed": true
  },
  {
    "userId": 8,
    "id": 158,
    "title": "debitis vitae delectus et harum accusamus aut deleniti a",
    "completed": true
  },
  {
    "userId": 8,
    "id": 159,
    "title": "debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis",
    "completed": true
  },
  {
    "userId": 8,
    "id": 160,
    "title": "et praesentium aliquam est",
    "completed": false
  },
  {
    "userId": 9,
    "id": 161,
    "title": "ex hic consequuntur earum omnis alias ut occaecati culpa",
    "completed": true
  },
  {
    "userId": 9,
    "id": 162,
    "title": "omnis laboriosam molestias animi sunt dolore",
    "completed": true
  },
  {
    "userId": 9,
    "id": 163,
    "title": "natus corrupti maxime laudantium et voluptatem laboriosam odit",
    "completed": false
  },
  {
    "userId": 9,
    "id": 164,
    "title": "reprehenderit quos aut aut consequatur est sed",

<div style="text-align:center;"><h4 style="color:#F7FF56;">GET Method:</h4></div>
<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
<p>The <strong>GET</strong> method is one of the main HTTP verbs and is used to <strong>retrieve data</strong> from a server.<br><br>
A GET request asks the server to return information without changing anything on it. It is commonly used to access public resources or fetch data from APIs.
<br><br>
Key characteristics:
<ul><li>Sends data through the URL.</li><li>Does not modify server state.</li><li>Safe and idempotent.</li></ul>
</div>
<div style="text-align:center;"><hr style="border: 0;height: 2px;background-color:#777777;width:50%;margin:25px auto;box-shadow: 0 2px 6px rgba(0,0,0,0.25);"></div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 2 :</h4>

<p style="color:#777777;">
Display on screen:
<p style="color:#777777;">
- The total number of each resource<br>
- The status code of each request)<br>
</p>

In [252]:
# Posts

print(" - Total:", len(posts.json()))
print(" - Status:", posts.status_code)

 - Total: 100
 - Status: 200

In [253]:
# Users

print(" - Total:", len(users.json()))
print(" - Status:", users.status_code)

 - Total: 10
 - Status: 200

In [254]:
# All

print(" - Total:", len(posts.json()))
print(" - Status:", todos.status_code)

 - Total: 100
 - Status: 200

<div style="text-align:center;"><h4 style="color:#F7FF56;">HTTP Status Codes:</h4></div><div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
<p>HTTP status codes indicate the result of a request made to a server.They show whether the operation was successful, redirected, invalid, or failed.<br><br>
Most important codes:
<ul><li><strong>200 OK</strong> – Successful request</li><li><strong>201 Created</strong> – A new resource was successfully created</li><li><strong>400 Bad Request</strong> – The request is invalid</li><li><strong>401 Unauthorized</strong> – Authentication is required</li><li><strong>404 Not Found</strong> – Resource not found</li><li><strong>500 Internal Server Error</strong> – Server encountered an error</li></ul></p>
</div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 3 :</h4>

<p style="color:#777777;">
Make a request to a non-existent post to get a 404 error and display the received status code.

</p>

In [255]:
# Error 404

y = requests.get("https://jsonplaceholder.typicode.com/posts/999999")
print("status_code :",y)

status_code : <Response [404]>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 4:</h4>

<p style="color:#777777;">
Make a POST request to create a new fictional publication. Includes title, message body and userId.
<p style="color:#777777;">
-Show JSON response<br>
-Show status code


</p>

In [256]:
# Post

post = requests.post(r"https://jsonplaceholder.typicode.com/posts", json={"id":10,
                                                                       "userId" : "NY08003",
                                                                       "title" : "Ninja Turtles",
                                                                       "body" : "The Ninja Turtles live underground in the dark, but with Italian names and pizza in their heart."})

print("JSON response:\n\n",post.json())
print("-" * 170)
print("\nStatus code:\n\n", post.status_code)

JSON response:

 {'id': 101, 'userId': 'NY08003', 'title': 'Ninja Turtles', 'body': 'The Ninja Turtles live underground in the dark, but with Italian names and pizza in their heart.'}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Status code:

 201

<div style="text-align:center;">
  <h4 style="color:#F7FF56;">POST Method:</h4>
</div>

<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
  <p>
    The <strong>POST</strong> method is used to <strong>send data</strong> to a server, usually to create a new resource.<br><br>
    POST requests include data in the body and can change the server’s state.
  </p>
</div>

<div style="text-align:center;">
  <hr style="border:0; height:2px; background-color:#777777; width:50%; margin:25px auto; box-shadow:0 2px 6px rgba(0,0,0,0.25);">
</div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 5:</h4>

<p style="color:#777777;">
Make a patch request to partially modify an existing publication.
<p style="color:#777777;">
-Show JSON response.<br>
-Show status code.


</p>

In [257]:
# Patch

patch = requests.patch(r"https://jsonplaceholder.typicode.com/posts/10", json={"userId" : "NY08003",
                                                                               "title" : "Ninja Turtles",
                                                                               "body" : "The Ninja Turtles fight all night, with pizza power and sewer might , Italian names in a New York shell, they’re heroes… but also smell."})

print("JSON response:\n\n",patch.json())
print("-" * 210)
print("\nStatus code:\n\n", patch.status_code)

JSON response:

 {'userId': 'NY08003', 'id': 10, 'title': 'Ninja Turtles', 'body': 'The Ninja Turtles fight all night, with pizza power and sewer might , Italian names in a New York shell, they’re heroes… but also smell.'}
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Status code:

 200

<div style="text-align:center;">
  <h4 style="color:#F7FF56;">PATCH Method:</h4>
</div>

<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
  <p>
    The <strong>PATCH</strong> method is used to <strong>partially update</strong> an existing resource on the server.<br><br>
    Unlike <strong>PUT</strong>, which replaces the entire resource, PATCH modifies only the specific fields sent in the request body.
  </p>
</div>

<div style="text-align:center;">
  <hr style="border:0; height:2px; background-color:#777777; width:50%; margin:25px auto; box-shadow:0 2px 6px rgba(0,0,0,0.25);">
</div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 6:</h4>

<p style="color:#777777;">
Make a DELETE request about a post.
<p style="color:#777777;">
-Show JSON response.<br>
-Show status code.

</p>

In [258]:
# Delete

delete = requests.delete(r"https://jsonplaceholder.typicode.com/posts/10", json={"id" : 10,
                                                                                 "userId" : "NY08003",
                                                                                 "title" : "Ninja Turtles",
                                                                                 "body" : "The Ninja Turtles fight all night, with pizza power and sewer might , Italian names in a New York shell, they’re heroes… but also smell."})


print("JSON response:\n",delete.json())
print("-" * 20)
print("\nStatus code:\n", delete.status_code)
print("-" * 20)

JSON response:
 {}
--------------------

Status code:
 200
--------------------

<div style="text-align:center;"><h4 style="color:#F7FF56;">DELETE Method:</h4></div>
<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
<p>The <strong>DELETE</strong> method is used to <strong>remove an existing resource</strong> from the server.<br><br>
It changes the server’s state and is often idempotent, meaning repeating the same DELETE request usually produces the same result.
<br><br>
Example use case:
Deleting a user, a post, or any stored item by its ID.
</p>
</div>
<div style="text-align:center;"><hr style="border: 0;height: 2px;background-color:#777777;width:50%;margin:25px auto;box-shadow: 0 2px 6px rgba(0,0,0,0.25);"></div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#17B978;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">


<div style="text-align:center;">

<h style="color:#17B978; font-size:32px; margin-bottom:10px;">
 <b2>LEVEL 2</b2></h><br><br>

<h style="color:#6F0000; font-size:24px; margin-bottom:10px;">
 <b2>Resource:</b2></h><br>
 <br>
<a href="https://github.com/public-apis/public-apis"  style="color:#F7FF56;">
   🔗 public-apis 🔗
</a>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 1 :</h4>

<p style="color:#777777;">
Explore the Public APIs repository and choose an API that allows GET requests.

</p>

<div style="text-align:center;">
    <h4 style="color:#F7FF56;">Solución :</h4>
</div>

<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">

<p>
I explored the Public APIs repository:<br><br>

<a href="https://github.com/public-apis/public-apis" style="color:#4A90E2;">
https://github.com/public-apis/public-apis
</a><br><br>

From this list, I chose the <strong>REST Countries API</strong>, available at:<br><br>

<a href="https://restcountries.com/" style="color:#4A90E2;">
https://restcountries.com/
</a><br><br>

This API fully supports GET requests and returns country-related data in JSON format.
</p>

</div>

<div style="text-align:center;">
<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">
</div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 2 :</h4>

<p style="color:#777777;">
Read the API documentation:
<p style="color:#777777;">
-Review the section with the available endpoints.<br>
 (In a markdown cell, write down at least two different endpoints)<br><br>
-Check whether the API offers interesting filters or optional parameters.<br>
 (In a markdown cell, write them down)<br><br>
-Verify that the response format is JSON. <br>
 (this is the most suitable for this exercise)<br>

<div style="text-align:center;"><h4 style="color:#F7FF56;">API Endpoints:</h4></div>
<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
<p>An <strong>API endpoint</strong> is a specific URL where a client can access a resource or perform an operation on a server.<br><br>
Each endpoint represents a function of the API and works together with HTTP methods like GET, POST, PUT, PATCH, or DELETE.
<br><br>
Examples of common endpoints:
<ul><li><strong>/users</strong> – Access or create users</li><li><strong>/users/{id}</strong> – Get, update, or delete a specific user</li><li><strong>/products</strong> – Retrieve or add products</li></ul>
<br>
Example full URL:
<strong>https://api.example.com/users/1</strong>
</p>
</div>
<div style="text-align:center;"><hr style="border: 0;height: 2px;background-color:#777777;width:50%;margin:25px auto;box-shadow: 0 2px 6px rgba(0,0,0,0.25);"></div>

In [259]:
# Checking

url = "https://restcountries.com/v3.1/all?fields=name,capital,region"

response = requests.get(url)

print("Status code:", response.status_code)

data = response.json()
print("First 3 results:")
for item in data[:3]:
    print(item)

Status code: 200
First 3 results:
{'name': {'common': 'Cook Islands', 'official': 'Cook Islands', 'nativeName': {'eng': {'official': 'Cook Islands', 'common': 'Cook Islands'}, 'rar': {'official': "Kūki 'Āirani", 'common': "Kūki 'Āirani"}}}, 'capital': ['Avarua'], 'region': 'Oceania'}
{'name': {'common': 'Guinea', 'official': 'Republic of Guinea', 'nativeName': {'fra': {'official': 'République de Guinée', 'common': 'Guinée'}}}, 'capital': ['Conakry'], 'region': 'Africa'}
{'name': {'common': 'Christmas Island', 'official': 'Territory of Christmas Island', 'nativeName': {'eng': {'official': 'Territory of Christmas Island', 'common': 'Christmas Island'}}}, 'capital': ['Flying Fish Cove'], 'region': 'Oceania'}

<div style="text-align:center;">
    <h4 style="color:#F7FF56;">Available Endpoints (REST Countries)</h4>
</div>

<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">

</p>
<strong>GET</strong> https://restcountries.com/v3.1/all <br>
&nbsp;&nbsp;Returns all countries with full details.<br><br>

<strong>GET</strong> https://restcountries.com/v3.1/name/{name} <br>
&nbsp;&nbsp;Returns information about a country by its name.<br>
&nbsp;&nbsp;Example: https://restcountries.com/v3.1/name/spain<br><br>

<strong>GET</strong> https://restcountries.com/v3.1/alpha/{code} <br>
&nbsp;&nbsp;Returns a country by its ISO code.<br>
&nbsp;&nbsp;Example: https://restcountries.com/v3.1/alpha/es
</p>

</div>

<div style="text-align:center;">
<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">
</div>

<div style="text-align:center;">
    <h4 style="color:#F7FF56;">Filters and Optional Parameters</h4>
</div>

<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">

<p>
The REST Countries API provides several optional query parameters:<br><br>

- <strong>fields</strong> → returns only selected fields <br>
&nbsp;&nbsp;Example:<br>
&nbsp;&nbsp;https://restcountries.com/v3.1/all?fields=name,capital,region<br><br>

- <strong>name</strong> → search by country name <br>
&nbsp;&nbsp;Example:<br>
&nbsp;&nbsp;https://restcountries.com/v3.1/name/peru<br><br>

- <strong>alpha</strong> → search by ISO code <br>
&nbsp;&nbsp;Example:<br>
&nbsp;&nbsp;https://restcountries.com/v3.1/alpha/it
</p>

</div>

<div style="text-align:center;">
<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">
</div>

<div style="text-align:center;">
    <h4 style="color:#F7FF56;">Response Format (JSON Verification)</h4>
</div>

<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">

<p>
All endpoints return data in <strong>JSON format</strong>.<br><br>

Example response (shortened):<br><br>

[<br>
&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;"name": { "common": "Spain" },<br>
&nbsp;&nbsp;&nbsp;&nbsp;"capital": ["Madrid"],<br>
&nbsp;&nbsp;&nbsp;&nbsp;"region": "Europe",<br>
&nbsp;&nbsp;&nbsp;&nbsp;"population": 47351567<br>
&nbsp;&nbsp;}<br>
]
</p>

</div>

<div style="text-align:center;">
<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">
</div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 3 :</h4>

<p style="color:#777777;">
Make a simple GET request:
<p style="color:#777777;">
-Display the status code of the response.<br>
-Clearly print some of the fields from the JSON response.

In [260]:
# Get , display and print

url = "https://restcountries.com/v3.1/name/spain"
response = requests.get(url)

print("Status code:", response.status_code)
print("-" * 60)
data = response.json()
country = data[0]

print("Country name:", country["name"]["common"])
print("Official name:", country["name"]["official"])
print("Capital:", country.get("capital", ["N/A"])[0])
print("Region:", country.get("region", "N/A"))
print("Population:", country.get("population", "N/A"))

Status code: 200
------------------------------------------------------------
Country name: Spain
Official name: Kingdom of Spain
Capital: Madrid
Region: Europe
Population: 49315949

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 4 :</h4>

<p style="color:#777777;">
Convert the data into a pandas DataFrame:
<p style="color:#777777;">
-Display the first rows of the DataFrame.

In [261]:
# Dataframe 

url = "https://restcountries.com/v3.1/all?fields=name,capital,region,population"
response = requests.get(url)
data = response.json()

clean_data = []

for country in data:
    clean_data.append({"name": country["name"]["common"],
                       "capital": country["capital"][0] if "capital" in country and country["capital"] else None,
                       "region": country.get("region", None),
                       "population": country.get("population", None)})

df = pd.DataFrame(clean_data)

df.head(10)

                 name           capital    region  population
0        Cook Islands            Avarua   Oceania       15040
1              Guinea           Conakry    Africa    14363931
2    Christmas Island  Flying Fish Cove   Oceania        1692
3                Togo              Lomé    Africa     8095498
4              Taiwan            Taipei      Asia    23317031
5          Kyrgyzstan           Bishkek      Asia     7281800
6            Suriname        Paramaribo  Americas      616500
7  Dominican Republic     Santo Domingo  Americas    10771504
8           Guatemala    Guatemala City  Americas    18079810
9             Algeria           Algiers    Africa    47400000

<hr style="
    border: 0;
    height: 2px;
    background-color:#17B978;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">


<div style="text-align:center;">

<h style="color:#17B978; font-size:32px; margin-bottom:10px;">
 <b2>LEVEL 3</b2></h><br><br>

<h style="color:#6F0000; font-size:24px; margin-bottom:10px;">
 <b2>Resource:</b2></h><br>
 <br>
<a href="https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS" style="color:#F7FF56;">
   🔗 open-data BCN 🔗
</a>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 1 :</h4>

<p style="color:#777777;">
Search for a dataset of your interest using package_search and package_show.
<p style="color:#777777;">
-Display the first rows of the DataFrame.

In [262]:
# Package_search

url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search"
params = {"q": "plaques fotovoltaiques"}

response = requests.get(url, params=params).json()
response

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_search',
 'success': True,
 'result': {'count': 2,
  'sort': 'fecha_publicacion desc',
  'facets': {},
  'results': [{'notes_translated': {'ca': 'Plaques fotovoltaiques  municipals a la ciutat de Barcelona',
     'en': 'Municipal photovoltaic panels in the city of Barcelona ',
     'es': 'Placas fotovoltaicas municipales en la ciudad de Barcelona '},
    'geolocation': 'Yes_with_map_view',
    'dades_alt_valor': 'Observacio_de_la_Terra_i_medi_ambient',
    'url_tornada': {'ca': 'https://www.energia.barcelona/ca/generar-energia/lajuntament-genera/mapa-de-generacio-fotovoltaica-municipal ',
     'en': 'https://www.energia.barcelona/en/generate-energy/city-council-generating/municipal-photovoltaic-energy-generation-map',
     'es': 'https://www.energia.barcelona/es/generar-energia/el-ayuntamiento-genera/mapa-de-generacion-fotovoltaica-municipal'},
    'dataset_fields_description': ' ',
    'fuente': 'Ajuntament de Barcelona',
    'tag': 'Plaques fotovoltaiques,Any 2022,Alt Valor,Any 2025',
    'private': False,
    'num_tags': 4,
    'code': 'plaques-fotovoltaiques',
    'frequency': 'PETICIO_NEGOCI',
    'id': '8b6fd878-f242-4e7f-b621-fa3ee605e8ca',
    'title_translated': {'ca': 'Plaques fotovoltaiques municipals a la ciutat de Barcelona',
     'en': 'Municipal photovoltaic panels in the city of Barcelona ',
     'es': 'Placas fotovoltaicas municipales en la ciudad de Barcelona '},
    'metadata_modified': '2025-10-28T07:30:05.084157',
    'author': 'Gerència Municipal ',
    'author_email': None,
    'isopen': True,
    'long_format': 'No',
    'state': 'active',
    'version': '',
    'mar_od': 'No',
    'relationships_as_object': [],
    'department': 'Agencia Local de Energía de Barcelona',
    'creator_user_id': '6d593275-d059-4261-9004-e6df8677e3bf',
    'type': 'dataset',
    'resources': [{'api_access_number_absolute': '3',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': '8b6fd878-f242-4e7f-b621-fa3ee605e8ca',
      'datastore_active': True,
      'id': 'add38a29-8412-4bf2-b7f5-2a7514a9d380',
      'description': '',
      'state': 'active',
      'api_access_number': '1',
      'size': '32155',
      'token_required': 'No',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '36',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2025_Installacions_Fotovoltaiques_Municipals.csv',
      'created': '2025-10-28T07:14:21.621951',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/8b6fd878-f242-4e7f-b621-fa3ee605e8ca/resource/add38a29-8412-4bf2-b7f5-2a7514a9d380/download',
      'downloads_absolute': '38',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-03-20T02:13:40.776108\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-10-29T02:12:00.368109\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2025-10-28T07:30:05.040301',
      'position': 0,
      'revision_id': '6b66eb87-a1a2-4691-a337-44903a21d120',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '8b6fd878-f242-4e7f-b621-fa3ee605e8ca',
      'datastore_active': True,
      'id': 'eb63730f-fc70-4000-800a-97edb6675da8',
      'size': '30927',
      'state': 'active',
      'api_access_number': '86',
      'api_access_number_absolute': '464',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '876',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'file_volum': 'little',
      'mimetype': None,
      'cache_url': None,
      'name': '2022_Installacions_Fotovoltaiques_Municipals .csv',
      'created': '2022-04-20T09:57:16.379095',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/8b6fd878-f242-4e7f-b621-fa3ee605e8ca/resource/eb63730f-fc70-4000-800a-97edb6675da8/download',
      'downloads_absolute': '1052',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-03-20T02:13:40.794798\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2022-04-21T02:06:30.879417\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2022-04-20T10:34:41.586597',
      'position': 1,
      'revision_id': '6b66eb87-a1a2-4691-a337-44903a21d120',
      'resource_type': None}],
    'token_required': 'No',
    'decalatgeNum': 'N/A',
    'tags': [{'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Alt Valor',
      'id': 'ebe20eba-8f65-40a9-9c25-4e7ab62b8f45',
      'name': 'Alt Valor'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2022',
      'id': '224016e4-81b8-4e60-819b-e7119ced7589',
      'name': 'Any 2022'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2025',
      'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
      'name': 'Any 2025'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Plaques fotovoltaiques',
      'id': 'e7d968bb-a73f-4e36-89b3-b53dc805f825',
      'name': 'Plaques fotovoltaiques'}],
    'ODS_Principal_agenda_2030': 'ODS 7: Energia neta i assequible',
    'fecha_publicacion': '2022-04-21',
    'ODS_Colateral2_agenda_2030': 'N/A',
    'ODS_Colateral1_agenda_2030': 'ODS 13: Acció climàtica',
    'license_id': 'CC-BY-4.0',
    'hide_url': 'No',
    'relationships_as_subject': [],
    'license_title': 'Creative Commons Attribution 4.0',
    'groups': [],
    'num_resources': 2,
    'organization': {'code': 'urbanisme-i-infraestructures',
     'display_name': 'Urbanisme i infraestructures',
     'description': 'Town planning and Infrastructures',
     'parent': {'code': 'territori',
      'display_name': 'Territori',
      'description': 'Territory',
      'created': '2017-01-24T16:55:06.680852',
      'package_count': 0,
      'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-territori',
      'description_translated': {'ca': 'Territori',
       'en': 'Territory',
       'es': 'Territorio'},
      'name': 'territori',
      'is_organization': True,
      'state': 'active',
      'image_url': 'bcn-icon2-territori',
      'groups': [],
      'type': 'organization',
      'title': 'Territory',
      'revision_id': '948d611b-5bfd-4878-a817-3bbdd28bae22',
      'title_translated': {'ca': 'Territori',
       'en': 'Territory',
       'es': 'Territorio'},
      'num_followers': 0,
      'id': 'fdb223be-3adc-4145-be97-980bcfbdaa3b',
      'approval_status': 'approved'},
     'created': '2017-01-24T16:55:07.057488',
     'package_count': 67,
     'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-urbanisme',
     'tematica_nti': 'urbanismo-infraestructuras',
     'description_translated': {'ca': 'Urbanisme i infraestructures',
      'en': 'Town planning and Infrastructures',
      'es': 'Urbanismo e infraestructuras'},
     'name': 'urbanisme-i-infraestructures',
     'is_organization': True,
     'state': 'active',
     'image_url': 'bcn-icon-urbanisme',
     'groups': [{'capacity': 'public', 'name': 'territori'}],
     'type': 'organization',
     'title': 'Town planning and Infrastructures',
     'revision_id': 'da18f861-8b29-45f5-88eb-ca5449896b24',
     'title_translated': {'ca': 'Urbanisme i infraestructures',
      'en': 'Town planning and Infrastructures',
      'es': 'Urbanismo e infraestructuras'},
     'num_followers': 0,
     'id': '9bf18787-464c-4355-b19e-697055626c77',
     'approval_status': 'approved'},
    'name': 'plaques-fotovoltaiques',
    'url': None,
    'notes': 'Municipal photovoltaic panels in the city of Barcelona ',
    'owner_org': '9bf18787-464c-4355-b19e-697055626c77',
    'load_type': 'ds_manual',
    'api': 'Yes',
    'license_url': 'https://creativecommons.org/licenses/by/4.0/',
    'historical': 'Yes',
    'title': 'Municipal photovoltaic panels in the city of Barcelona ',
    'revision_id': 'ec56b4fb-5bef-4ce1-a134-a8113da7520a',
    'extras': [{'key': '01.Any_Alta', 'value': 'Any alta de la instal·lació'},
     {'key': '02.Tipus_Equipament', 'value': "Tipus d'instal·lació"},
     {'key': '03.Tipologia_Sigles ( Només a 2022)',
      'value': 'Sigles de la tipologia __[Tipologies de les plaques fotovoltaiques municipals a la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/plaques-fotovoltaiques-tipologia) __'},
     {'key': '04.Subtipologia_Sigles (Només  a 2022)',
      'value': 'Sigles de la subtipologia __[Tipologies de les plaques fotovoltaiques municipals a la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/plaques-fotovoltaiques-tipologia)__'},
     {'key': '05.Nom', 'value': 'Nom de la instal·lació'},
     {'key': '06.Adreca', 'value': 'Adreça de la instal·lació'},
     {'key': '07.Latitud', 'value': 'Latitud'},
     {'key': '08.Longitud', 'value': 'Longitud'},
     {'key': '09.Codi_Districte', 'value': 'Codi del districte'},
     {'key': '10.Nom_districte', 'value': 'Nom del districte'},
     {'key': '11.Codi_Barri (Només a 2022)', 'value': 'Codi del barri'},
     {'key': '12.Nom_Barri (Només a 2022)', 'value': 'Nom del barri'},
     {'key': '13.Potencia_kWp  ', 'value': 'Potència'},
     {'key': '14. Energia_Produeix_ kWh ', 'value': 'Energia que produeix'},
     {'key': '15.Nombre_Llars_Subministrament',
      'value': 'Nombre d ellars que pot subministrar'},
     {'key': '16.Emissions_ Estalviades_KgCO2 ',
      'value': 'Emissions estalviades'},
     {'key': '17.Tipus_Connexio/ Autoconsum_xarxa ( a partir de 2025)',
      'value': 'Tipus de connexió'}]},
   {'notes_translated': {'ca': 'Tipologies i subtipologies de les plaques fotovoltaiques municipals a la ciutat de Barcelona',
     'en': 'Types  and subtypes of municipal photovoltaic panels in the city of Barcelona',
     'es': 'Tipologías y subtipologias de las placas fotovoltaicas municipales en la ciudad de Barcelona'},
    'geolocation': 'No',
    'dades_alt_valor': 'Observacio_de_la_Terra_i_medi_ambient',
    'url_tornada': {'ca': 'https://www.energia.barcelona/ca/',
     'en': 'https://www.energia.barcelona/en/',
     'es': 'https://www.energia.barcelona/es/'},
    'dataset_fields_description': '',
    'fuente': 'Ajuntament de Barcelona',
    'tag': 'Plaques fotovoltaiques,Alt Valor',
    'private': False,
    'num_tags': 2,
    'code': 'plaques-fotovoltaiques-tipologia',
    'frequency': 'PETICIO_NEGOCI',
    'id': 'b29a6068-93f0-4593-9908-28415bf32190',
    'title_translated': {'ca': 'Tipologies de les plaques fotovoltaiques municipals a la ciutat de Barcelona',
     'en': 'Types of municipal photovoltaic panels in the city of Barcelona',
     'es': 'Tipologías de las placas fotovoltaicas municipales en la ciudad de Barcelona'},
    'metadata_modified': '2025-09-23T10:46:27.238448',
    'author': 'Gerència Municipal',
    'author_email': None,
    'isopen': True,
    'long_format': 'Yes',
    'state': 'active',
    'version': '',
    'mar_od': 'No',
    'relationships_as_object': [],
    'department': 'Agencia Local de Energía de Barcelona',
    'creator_user_id': '6d593275-d059-4261-9004-e6df8677e3bf',
    'type': 'dataset',
    'resources': [{'cache_last_updated': None,
      'token_type': '',
      'package_id': 'b29a6068-93f0-4593-9908-28415bf32190',
      'datastore_active': True,
      'id': '19e3f838-073d-4d58-9172-8f7065ec6e2b',
      'size': '5200',
      'state': 'active',
      'api_access_number': '11',
      'api_access_number_absolute': '13',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '884',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'file_volum': 'little',
      'mimetype': None,
      'cache_url': None,
      'name': 'Installacions_Fotovoltaiques_Municipals _Tipologies.csv',
      'created': '2022-04-19T09:17:41.733497',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/b29a6068-93f0-4593-9908-28415bf32190/resource/19e3f838-073d-4d58-9172-8f7065ec6e2b/download',
      'downloads_absolute': '958',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-03-20T02:13:41.272576\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2022-04-20T02:06:29.545578\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2022-04-22T06:01:41.228957',
      'position': 0,
      'revision_id': '2ffdc183-4dc7-423e-987f-91bf561fd0d3',
      'resource_type': None}],
    'token_required': 'No',
    'decalatgeNum': 'N/A',
    'tags': [{'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Alt Valor',
      'id': 'ebe20eba-8f65-40a9-9c25-4e7ab62b8f45',
      'name': 'Alt Valor'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Plaques fotovoltaiques',
      'id': 'e7d968bb-a73f-4e36-89b3-b53dc805f825',
      'name': 'Plaques fotovoltaiques'}],
    'ODS_Principal_agenda_2030': 'ODS 7: Energia neta i assequible',
    'fecha_publicacion': '2022-04-21',
    'ODS_Colateral2_agenda_2030': 'N/A',
    'ODS_Colateral1_agenda_2030': 'ODS 13: Acció climàtica',
    'license_id': 'CC-BY-4.0',
    'hide_url': 'No',
    'relationships_as_subject': [],
    'license_title': 'Creative Commons Attribution 4.0',
    'groups': [],
    'num_resources': 1,
    'organization': {'code': 'urbanisme-i-infraestructures',
     'display_name': 'Urbanisme i infraestructures',
     'description': 'Town planning and Infrastructures',
     'parent': {'code': 'territori',
      'display_name': 'Territori',
      'description': 'Territory',
      'created': '2017-01-24T16:55:06.680852',
      'package_count': 0,
      'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-territori',
      'description_translated': {'ca': 'Territori',
       'en': 'Territory',
       'es': 'Territorio'},
      'name': 'territori',
      'is_organization': True,
      'state': 'active',
      'image_url': 'bcn-icon2-territori',
      'groups': [],
      'type': 'organization',
      'title': 'Territory',
      'revision_id': '948d611b-5bfd-4878-a817-3bbdd28bae22',
      'title_translated': {'ca': 'Territori',
       'en': 'Territory',
       'es': 'Territorio'},
      'num_followers': 0,
      'id': 'fdb223be-3adc-4145-be97-980bcfbdaa3b',
      'approval_status': 'approved'},
     'created': '2017-01-24T16:55:07.057488',
     'package_count': 67,
     'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-urbanisme',
     'tematica_nti': 'urbanismo-infraestructuras',
     'description_translated': {'ca': 'Urbanisme i infraestructures',
      'en': 'Town planning and Infrastructures',
      'es': 'Urbanismo e infraestructuras'},
     'name': 'urbanisme-i-infraestructures',
     'is_organization': True,
     'state': 'active',
     'image_url': 'bcn-icon-urbanisme',
     'groups': [{'capacity': 'public', 'name': 'territori'}],
     'type': 'organization',
     'title': 'Town planning and Infrastructures',
     'revision_id': 'da18f861-8b29-45f5-88eb-ca5449896b24',
     'title_translated': {'ca': 'Urbanisme i infraestructures',
      'en': 'Town planning and Infrastructures',
      'es': 'Urbanismo e infraestructuras'},
     'num_followers': 0,
     'id': '9bf18787-464c-4355-b19e-697055626c77',
     'approval_status': 'approved'},
    'name': 'plaques-fotovoltaiques-tipologia',
    'url': None,
    'notes': 'Types  and subtypes of municipal photovoltaic panels in the city of Barcelona',
    'owner_org': '9bf18787-464c-4355-b19e-697055626c77',
    'load_type': 'ds_manual',
    'api': 'Yes',
    'license_url': 'https://creativecommons.org/licenses/by/4.0/',
    'historical': 'No',
    'title': 'Types of municipal photovoltaic panels in the city of Barcelona',
    'revision_id': '197eb446-0c94-45de-bcb3-7590fe698c57',
    'extras': [{'key': '01.Tipologia_Sigles',
      'value': 'Sigles de la tipologia'},
     {'key': '02.Tipologia_Descripcio', 'value': 'Descripció de la tipologia'},
     {'key': '03.Subtipologia_Sigles', 'value': 'Sigles de la subtipologia'},
     {'key': '04.Subtipologia_Descripcio',
      'value': 'Descripció de la subtipologia'}]}],
  'search_facets': {}}}

<div style="text-align:center;"><h4 style="color:#F7FF56;">Package Search:</h4></div>
<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
<p>A <strong>package search</strong> refers to an API endpoint or service that allows clients to <strong>look up packages</strong> by name, ID, category, or keywords.<br><br>
It is commonly used in systems that manage software packages, shipments, products, or library modules.
<br><br>
Typical operations:
<ul><li>Search by package name or keyword</li><li>Filter by version, category, or status</li><li>Retrieve package details from a registry or database</li></ul>
<br>
Example endpoint:
<strong>/packages/search?query=express</strong>
</p>
</div>
<div style="text-align:center;"><hr style="border: 0;height: 2px;background-color:#777777;width:50%;margin:25px auto;box-shadow: 0 2px 6px rgba(0,0,0,0.25);"></div>

In [263]:
# Package_show

dataset_id = "plaques-fotovoltaiques"
show_url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show"

dataset_info = requests.get(show_url, params={"id": dataset_id}).json()
dataset_info

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_show',
 'success': True,
 'result': {'notes_translated': {'ca': 'Plaques fotovoltaiques  municipals a la ciutat de Barcelona',
   'en': 'Municipal photovoltaic panels in the city of Barcelona ',
   'es': 'Placas fotovoltaicas municipales en la ciudad de Barcelona '},
  'geolocation': 'Yes_with_map_view',
  'dades_alt_valor': 'Observacio_de_la_Terra_i_medi_ambient',
  'url_tornada': {'ca': 'https://www.energia.barcelona/ca/generar-energia/lajuntament-genera/mapa-de-generacio-fotovoltaica-municipal ',
   'en': 'https://www.energia.barcelona/en/generate-energy/city-council-generating/municipal-photovoltaic-energy-generation-map',
   'es': 'https://www.energia.barcelona/es/generar-energia/el-ayuntamiento-genera/mapa-de-generacion-fotovoltaica-municipal'},
  'dataset_fields_description': ' ',
  'fuente': 'Ajuntament de Barcelona',
  'tag': 'Plaques fotovoltaiques,Any 2022,Alt Valor,Any 2025',
  'private': False,
  'num_tags': 4,
  'code': 'plaques-fotovoltaiques',
  'frequency': 'PETICIO_NEGOCI',
  'id': '8b6fd878-f242-4e7f-b621-fa3ee605e8ca',
  'title_translated': {'ca': 'Plaques fotovoltaiques municipals a la ciutat de Barcelona',
   'en': 'Municipal photovoltaic panels in the city of Barcelona ',
   'es': 'Placas fotovoltaicas municipales en la ciudad de Barcelona '},
  'metadata_modified': '2025-10-28T07:30:05.084157',
  'author': 'Gerència Municipal ',
  'author_email': None,
  'isopen': True,
  'long_format': 'No',
  'state': 'active',
  'version': '',
  'mar_od': 'No',
  'relationships_as_object': [],
  'department': 'Agencia Local de Energía de Barcelona',
  'creator_user_id': '6d593275-d059-4261-9004-e6df8677e3bf',
  'type': 'dataset',
  'resources': [{'api_access_number_absolute': 3,
    'cache_last_updated': None,
    'incorporated_in_cityos_res': 'No',
    'token_type': '',
    'package_id': '8b6fd878-f242-4e7f-b621-fa3ee605e8ca',
    'datastore_active': True,
    'id': 'add38a29-8412-4bf2-b7f5-2a7514a9d380',
    'description': '',
    'state': 'active',
    'api_access_number': 1,
    'size': '32155',
    'token_required': 'No',
    'hash': '',
    'token_name': '',
    'format': 'CSV',
    'downloads': 36,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'column_types': '',
    'hide_url': 'No',
    'token_version': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2025_Installacions_Fotovoltaiques_Municipals.csv',
    'created': '2025-10-28T07:14:21.621951',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/8b6fd878-f242-4e7f-b621-fa3ee605e8ca/resource/add38a29-8412-4bf2-b7f5-2a7514a9d380/download/2025_installacions_fotovoltaiques_municipals.csv',
    'downloads_absolute': 38,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-03-20T02:13:40.776108',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-10-29T02:12:00.368109',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2025-10-28T07:30:05.040301',
    'position': 0,
    'revision_id': '6b66eb87-a1a2-4691-a337-44903a21d120',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '8b6fd878-f242-4e7f-b621-fa3ee605e8ca',
    'datastore_active': True,
    'id': 'eb63730f-fc70-4000-800a-97edb6675da8',
    'size': '30927',
    'state': 'active',
    'api_access_number': 86,
    'api_access_number_absolute': 464,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 876,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'file_volum': 'little',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_Installacions_Fotovoltaiques_Municipals .csv',
    'created': '2022-04-20T09:57:16.379095',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/8b6fd878-f242-4e7f-b621-fa3ee605e8ca/resource/eb63730f-fc70-4000-800a-97edb6675da8/download/2022_installacions_fotovoltaiques_municipals-.csv',
    'downloads_absolute': 1052,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-03-20T02:13:40.794798',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2022-04-21T02:06:30.879417',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2022-04-20T10:34:41.586597',
    'position': 1,
    'revision_id': '6b66eb87-a1a2-4691-a337-44903a21d120',
    'resource_type': None}],
  'token_required': 'No',
  'decalatgeNum': 'N/A',
  'tags': [{'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Alt Valor',
    'id': 'ebe20eba-8f65-40a9-9c25-4e7ab62b8f45',
    'name': 'Alt Valor'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2022',
    'id': '224016e4-81b8-4e60-819b-e7119ced7589',
    'name': 'Any 2022'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2025',
    'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
    'name': 'Any 2025'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Plaques fotovoltaiques',
    'id': 'e7d968bb-a73f-4e36-89b3-b53dc805f825',
    'name': 'Plaques fotovoltaiques'}],
  'ODS_Principal_agenda_2030': 'ODS 7: Energia neta i assequible',
  'fecha_publicacion': '2022-04-21',
  'ODS_Colateral2_agenda_2030': 'N/A',
  'ODS_Colateral1_agenda_2030': 'ODS 13: Acció climàtica',
  'license_id': 'CC-BY-4.0',
  'hide_url': 'No',
  'relationships_as_subject': [],
  'license_title': 'Creative Commons Attribution 4.0',
  'groups': [],
  'num_resources': 2,
  'organization': {'description': '',
   'created': '2017-01-24T16:55:07.057488',
   'title': 'Urbanisme i infraestructures',
   'name': 'urbanisme-i-infraestructures',
   'is_organization': True,
   'state': 'active',
   'image_url': 'bcn-icon-urbanisme',
   'revision_id': 'da18f861-8b29-45f5-88eb-ca5449896b24',
   'type': 'organization',
   'id': '9bf18787-464c-4355-b19e-697055626c77',
   'approval_status': 'approved'},
  'name': 'plaques-fotovoltaiques',
  'url': None,
  'notes': 'Municipal photovoltaic panels in the city of Barcelona ',
  'owner_org': '9bf18787-464c-4355-b19e-697055626c77',
  'load_type': 'ds_manual',
  'qa': {'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.',
   'updated': '2026-03-20T02:13:40.794798',
   'openness_score': 3},
  'api': 'Yes',
  'license_url': 'https://creativecommons.org/licenses/by/4.0/',
  'historical': 'Yes',
  'title': 'Municipal photovoltaic panels in the city of Barcelona ',
  'revision_id': 'ec56b4fb-5bef-4ce1-a134-a8113da7520a',
  'extras': [{'key': '01.Any_Alta', 'value': 'Any alta de la instal·lació'},
   {'key': '02.Tipus_Equipament', 'value': "Tipus d'instal·lació"},
   {'key': '03.Tipologia_Sigles ( Només a 2022)',
    'value': 'Sigles de la tipologia __[Tipologies de les plaques fotovoltaiques municipals a la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/plaques-fotovoltaiques-tipologia) __'},
   {'key': '04.Subtipologia_Sigles (Només  a 2022)',
    'value': 'Sigles de la subtipologia __[Tipologies de les plaques fotovoltaiques municipals a la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/plaques-fotovoltaiques-tipologia)__'},
   {'key': '05.Nom', 'value': 'Nom de la instal·lació'},
   {'key': '06.Adreca', 'value': 'Adreça de la instal·lació'},
   {'key': '07.Latitud', 'value': 'Latitud'},
   {'key': '08.Longitud', 'value': 'Longitud'},
   {'key': '09.Codi_Districte', 'value': 'Codi del districte'},
   {'key': '10.Nom_districte', 'value': 'Nom del districte'},
   {'key': '11.Codi_Barri (Només a 2022)', 'value': 'Codi del barri'},
   {'key': '12.Nom_Barri (Només a 2022)', 'value': 'Nom del barri'},
   {'key': '13.Potencia_kWp  ', 'value': 'Potència'},
   {'key': '14. Energia_Produeix_ kWh ', 'value': 'Energia que produeix'},
   {'key': '15.Nombre_Llars_Subministrament',
    'value': 'Nombre d ellars que pot subministrar'},
   {'key': '16.Emissions_ Estalviades_KgCO2 ',
    'value': 'Emissions estalviades'},
   {'key': '17.Tipus_Connexio/ Autoconsum_xarxa ( a partir de 2025)',
    'value': 'Tipus de connexió'}]}}

<div style="text-align:center;"><h4 style="color:#F7FF56;">Package Show:</h4></div>
<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
<p>A <strong>package_show</strong> endpoint is used to <strong>retrieve detailed information</strong> about a specific package.<br><br>
It typically returns full metadata such as name, version, description, author, dependencies, and other relevant fields.
<br><br>
This operation is common in package registries, software repositories, and API catalog systems. <br><br>
</div>
<div style="text-align:center;"><hr style="border: 0;height: 2px;background-color:#777777;width:50%;margin:25px auto;box-shadow: 0 2px 6px rgba(0,0,0,0.25);"></div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 2 :</h4>

<p style="color:#777777;">From the results obtained, select one that has resources available in CSV or JSON format.

In [264]:
# Show results:

for r in dataset_info["result"]["resources"]:
    print(r["name"], r["format"], r["id"])

2025_Installacions_Fotovoltaiques_Municipals.csv CSV add38a29-8412-4bf2-b7f5-2a7514a9d380
2022_Installacions_Fotovoltaiques_Municipals .csv CSV eb63730f-fc70-4000-800a-97edb6675da8

<div style="text-align:center;"><h4 style="color:#F7FF56;">Selected Resource (Open Data BCN)</h4></div>
<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
<strong>FORMAT:</strong> CSV <br>   The resource is available in CSV format, which satisfies the requirement of selecting a CSV or JSON resource.<br><br>
<strong>RESOURCE ID:</strong> add38a29-8412-4bf2-b7f5-2a7514a9d380 <br>   This is the identifier used to query the dataset through the <code>datastore_search</code> API.<br><br>
</div>
<div style="text-align:center;"><hr style="border: 0;height: 2px;background-color:#777777;width:50%;margin:25px auto;box-shadow: 0 2px 6px rgba(0,0,0,0.25);"></div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 3 :</h4>

<p style="color:#777777;">
Using the resource_id of the selected resource, make a query with datastore_search to:
Retrieve at least 100 records.

In [265]:
# Resource_id 

resource_id = "add38a29-8412-4bf2-b7f5-2a7514a9d380"
data_url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search"

params = {"resource_id": resource_id,"limit": 211}

response = requests.get(data_url, params=params).json()

records = response["result"]["records"]
records

[{'Nom': 'Edifici Nou i Novíssim',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '46',
  'Energia_Produeix_ kWh': '105800',
  'Nom_Districte': 'Ciutat Vella',
  'Emissions_ Estalviades_KgCO2': '38088',
  'Longitude': '2.177636994021850',
  'Codi_Districte': '1',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '84.64',
  'Any_Alta': '2000',
  'Latitude': '41.3817393706',
  '_id': 1,
  'Adreca': 'Plaça Sant Miquel, 1'},
 {'Nom': 'CEIP Costa i Llobera',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Sarrià-Sant Gervasi',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.108931198056360',
  'Codi_Districte': '5',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2002',
  'Latitude': '41.402116173325400',
  '_id': 2,
  'Adreca': 'Carrer de la Capella de Can Caralleu, 3'},
 {'Nom': 'CEIP Tàber',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '16',
  'Energia_Produeix_ kWh': '37606',
  'Nom_Districte': 'Sarrià-Sant Gervasi',
  'Emissions_ Estalviades_KgCO2': '13538',
  'Longitude': '2.112299569219710',
  'Codi_Districte': '5',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '30.08',
  'Any_Alta': '2002',
  'Latitude': '41.401224466632500',
  '_id': 3,
  'Adreca': 'Carrer Esports, 9'},
 {'Nom': "CEIP Font d'en Fargas",
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Horta-Guinardó',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.165784055730250',
  'Codi_Districte': '7',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2002',
  'Latitude': '41.422796879358100',
  '_id': 4,
  'Adreca': "Passeig Font d'en Fargues, 65"},
 {'Nom': 'Pèrgola de Vallbona',
  'Tipus_Equipament': 'Espai públic',
  'Nombre_Llars_Subministrament': '38',
  'Energia_Produeix_ kWh': '86400',
  'Nom_Districte': 'Nou Barris',
  'Emissions_ Estalviades_KgCO2': '31104',
  'Longitude': '2.186297977432090',
  'Codi_Districte': '8',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '86.4',
  'Any_Alta': '2002',
  'Latitude': '41.465160742776000',
  '_id': 5,
  'Adreca': 'Carrer Castelladral 6-10'},
 {'Nom': 'Institut FP Narcís Monturiol',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Ciutat Vella',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.191699990468070',
  'Codi_Districte': '1',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2003',
  'Latitude': '41.381052513451700',
  '_id': 6,
  'Adreca': 'Passeig Salvat Papasseït s/n'},
 {'Nom': 'IES M. Bosc de Montjuïc',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Sants-Montjuïc',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.161529484565170',
  'Codi_Districte': '3',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2003',
  'Latitude': '41.369353666614800',
  '_id': 7,
  'Adreca': 'Avinguda Miramar, 9'},
 {'Nom': 'IES M. Serrat i Bonastre',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '2',
  'Energia_Produeix_ kWh': '3600',
  'Nom_Districte': 'Sarrià-Sant Gervasi',
  'Emissions_ Estalviades_KgCO2': '1296',
  'Longitude': '2.148025009690350',
  'Codi_Districte': '5',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '2.88',
  'Any_Alta': '2003',
  'Latitude': '41.406764919077000',
  '_id': 8,
  'Adreca': 'Carrer Marquès de Santa Anna, 4'},
 {'Nom': 'IES Anna Gironella de Mundet',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Horta-Guinardó',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.143536213704960',
  'Codi_Districte': '7',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2003',
  'Latitude': '41.437066315843500',
  '_id': 9,
  'Adreca': "Carrer d'Olympe de Gouges, s/n"},
 {'Nom': 'IES M. Ferran Tallada',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Horta-Guinardó',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.163458184566790',
  'Codi_Districte': '7',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2003',
  'Latitude': '41.420645431925100',
  '_id': 10,
  'Adreca': 'Carrer Gran Vista, 54'},
 {'Nom': 'CEIP M. Escola del Mar',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Horta-Guinardó',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.170107182710400',
  'Codi_Districte': '7',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2003',
  'Latitude': '41.418097454215600',
  '_id': 11,
  'Adreca': 'Carrer Gènova, 12'},
 {'Nom': 'Biblioteca Ignasi Iglesias – Can Fabra. Façana',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '2',
  'Energia_Produeix_ kWh': '5410',
  'Nom_Districte': 'Sant Andreu',
  'Emissions_ Estalviades_KgCO2': '1948',
  'Longitude': '2.191482082710950',
  'Codi_Districte': '9',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '5.41',
  'Any_Alta': '2003',
  'Latitude': '41.435302344134500',
  '_id': 12,
  'Adreca': 'Carrer del Segre, 22-32'},
 {'Nom': 'CEE M. Pont del Dragó',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Sant Andreu',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.190743326893750',
  'Codi_Districte': '9',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2003',
  'Latitude': '41.427243001737100',
  '_id': 13,
  'Adreca': 'Carrer Sagrera, 179'},
 {'Nom': 'IES M. Joan Manuel Zafra',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Sant Martí',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.182832596200300',
  'Codi_Districte': '10',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2003',
  'Latitude': '41.410282150063800',
  '_id': 14,
  'Adreca': 'Carrer Rogent, 51'},
 {'Nom': 'Fustes Gilabert (Padilla 210). Mitgera',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '1',
  'Energia_Produeix_ kWh': '3200',
  'Nom_Districte': 'Eixample',
  'Emissions_ Estalviades_KgCO2': '1152',
  'Longitude': '2.179538311546550',
  'Codi_Districte': '2',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '3.2',
  'Any_Alta': '2004',
  'Latitude': '41.404155183574100',
  '_id': 15,
  'Adreca': 'Carrer Padilla, 210'},
 {'Nom': 'Biblioteca Juan Marsé',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6750',
  'Nom_Districte': 'Horta-Guinardó',
  'Emissions_ Estalviades_KgCO2': '2430',
  'Longitude': '2.155056855730200',
  'Codi_Districte': '7',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '5.4',
  'Any_Alta': '2006',
  'Latitude': '41.421202192886700',
  '_id': 16,
  'Adreca': 'Carrer Murtra, 135-145'},
 {'Nom': 'Escola Adults Barceloneta',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '4',
  'Energia_Produeix_ kWh': '9600',
  'Nom_Districte': 'Ciutat Vella',
  'Emissions_ Estalviades_KgCO2': '3456',
  'Longitude': '2.188275898055720',
  'Codi_Districte': '1',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '7.68',
  'Any_Alta': '2008',
  'Latitude': '41.382469529331100',
  '_id': 17,
  'Adreca': 'Carrer Balboa, 11'},
 {'Nom': 'Centre Cultural Casa Elizalde',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6000',
  'Nom_Districte': 'Eixample',
  'Emissions_ Estalviades_KgCO2': '2160',
  'Longitude': '2.165840098056100',
  'Codi_Districte': '2',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '4.8',
  'Any_Alta': '2008',
  'Latitude': '41.394630540169100',
  '_id': 18,
  'Adreca': 'Carrer València, 302'},
 {'Nom': 'Centre Cívic El Sortidor',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '7750',
  'Nom_Districte': 'Sants-Montjuïc',
  'Emissions_ Estalviades_KgCO2': '2790',
  'Longitude': '2.162433280852640',
  'Codi_Districte': '3',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '6.2',
  'Any_Alta': '2008',
  'Latitude': '41.372257709624700',
  '_id': 19,
  'Adreca': 'Plaça del Sortidor, 12'},
 {'Nom': 'Centre Cívic Anníbal',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '6',
  'Energia_Produeix_ kWh': '13950',
  'Nom_Districte': 'Sants-Montjuïc',
  'Emissions_ Estalviades_KgCO2': '5022',
  'Longitude': '2.162424855728620',
  'Codi_Districte': '3',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '11.16',
  'Any_Alta': '2008',
  'Latitude': '41.371905802764900',
  '_id': 20,
  'Adreca': 'Carrer Anníbal, 4-6'},
 {'Nom': 'Biblioteca Vapor Vell',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '7',
  'Energia_Produeix_ kWh': '15525',
  'Nom_Districte': 'Sants-Montjuïc',
  'Emissions_ Estalviades_KgCO2': '5589',
  'Longitude': '2.134963455728780',
  'Codi_Districte': '3',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '12.42',
  'Any_Alta': '2008',
  'Latitude': '41.376962694260700',
  '_id': 21,
  'Adreca': 'Passatge del Vapor Vell s/n'},
 {'Nom': 'Biblioteca Francesc Candel. Façana',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '11',
  'Energia_Produeix_ kWh': '25200',
  'Nom_Districte': 'Sants-Montjuïc',
  'Emissions_ Estalviades_KgCO2': '9072',
  'Longitude': '2.136119798055060',
  'Codi_Districte': '3',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '25.2',
  'Any_Alta': '2008',
  'Latitude': '41.361650273027300',
  '_id': 22,
  'Adreca': "Carrer de l'Amnistia Internacional, 10"},
 {'Nom': 'Seu del districte de Les Corts',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '2',
  'Energia_Produeix_ kWh': '3600',
  'Nom_Districte': 'Les Corts',
  'Emissions_ Estalviades_KgCO2': '1296',
  'Longitude': '2.129733682709370',
  'Codi_Districte': '4',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '2.88',
  'Any_Alta': '2008',
  'Latitude': '41.385884370789100',
  '_id': 23,
  'Adreca': 'Plaça Comas, 18'},
 {'Nom': 'Centre Cívic Vázquez Montalbán',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '12',
  'Energia_Produeix_ kWh': '28350',
  'Nom_Districte': 'Sarrià-Sant Gervasi',
  'Emissions_ Estalviades_KgCO2': '10206',
  'Longitude': '2.102880098056770',
  'Codi_Districte': '5',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '22.68',
  'Any_Alta': '2008',
  'Latitude': '41.415387113994000',
  '_id': 24,
  'Adreca': "Carrer d'Elisa Moragas i Badia, 16-34"},
 {'Nom': 'Edifici SUMA',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6563',
  'Nom_Districte': 'Gràcia',
  'Emissions_ Estalviades_KgCO2': '2363',
  'Longitude': '2.152611653873420',
  'Codi_Districte': '6',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '5.25',
  'Any_Alta': '2008',
  'Latitude': '41.406434872853400',
  '_id': 25,
  'Adreca': "Carrer Torrent de l'Olla, 218-220"},
 {'Nom': 'Escola Bressol Sant Medir. Façana',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '5',
  'Energia_Produeix_ kWh': '12480',
  'Nom_Districte': 'Gràcia',
  'Emissions_ Estalviades_KgCO2': '4493',
  'Longitude': '2.152900382709920',
  'Codi_Districte': '6',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '12.48',
  'Any_Alta': '2008',
  'Latitude': '41.403431127334700',
  '_id': 26,
  'Adreca': 'Carrer de Santa Rosa, 7'},
 {'Nom': 'Centre Osi',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '6080',
  'Nom_Districte': 'Gràcia',
  'Emissions_ Estalviades_KgCO2': '2189',
  'Longitude': '2.152324704923830',
  'Codi_Districte': '6',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '6.08',
  'Any_Alta': '2008',
  'Latitude': '41.403311137715900',
  '_id': 27,
  'Adreca': 'Carrer Gran de Gràcia, 190-192'},
 {'Nom': 'Centre Cívic Carmel',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '4',
  'Energia_Produeix_ kWh': '9625',
  'Nom_Districte': 'Gràcia',
  'Emissions_ Estalviades_KgCO2': '3465',
  'Longitude': '2.151066867364020',
  'Codi_Districte': '6',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '7.7',
  'Any_Alta': '2008',
  'Latitude': '41.420458521070100',
  '_id': 28,
  'Adreca': 'Carrer Santuaris, 27'},
 {'Nom': "Casal de Gent Gran Vall d'Hebron",
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '7',
  'Energia_Produeix_ kWh': '16800',
  'Nom_Districte': 'Horta-Guinardó',
  'Emissions_ Estalviades_KgCO2': '6048',
  'Longitude': '2.146981198057300',
  'Codi_Districte': '7',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '13.44',
  'Any_Alta': '2008',
  'Latitude': '41.432481880106300',
  '_id': 29,
  'Adreca': 'Carrer Arquitecte Moragas, 5'},
 {'Nom': 'Biblioteca Les Roquetes',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '8',
  'Energia_Produeix_ kWh': '17250',
  'Nom_Districte': 'Nou Barris',
  'Emissions_ Estalviades_KgCO2': '6210',
  'Longitude': '2.176776455730960',
  'Codi_Districte': '8',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '13.8',
  'Any_Alta': '2008',
  'Latitude': '41.445222497074800',
  '_id': 30,
  'Adreca': 'Via Favència, 288'},
 {'Nom': 'Casal de Gent Gran Navas',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '3',
  'Energia_Produeix_ kWh': '7750',
  'Nom_Districte': 'Sant Andreu',
  'Emissions_ Estalviades_KgCO2': '2790',
  'Longitude': '2.181680655912',
  'Codi_Districte': '9',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '6.2',
  'Any_Alta': '2008',
  'Latitude': '41.418737732467',
  '_id': 31,
  'Adreca': 'Carrer Capella s/n'},
 {'Nom': 'Pèrgola de Bon Pastor',
  'Tipus_Equipament': 'Espai públic',
  'Nombre_Llars_Subministrament': '47',
  'Energia_Produeix_ kWh': '107800',
  'Nom_Districte': 'Sant Andreu',
  'Emissions_ Estalviades_KgCO2': '38808',
  'Longitude': '2.208935300192',
  'Codi_Districte': '9',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '107.8',
  'Any_Alta': '2008',
  'Latitude': '41.436820297576',
  '_id': 32,
  'Adreca': "Carrer de l'Avançada, 1"},
 {'Nom': 'Masia de Can cadena',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '5',
  'Energia_Produeix_ kWh': '10463',
  'Nom_Districte': 'Sant Martí',
  'Emissions_ Estalviades_KgCO2': '3767',
  'Longitude': '2.195306113403',
  'Codi_Districte': '10',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '8.37',
  'Any_Alta': '2008',
  'Latitude': '41.418660598555',
  '_id': 33,
  'Adreca': 'Carrer Menorca, 25'},
 {'Nom': 'Centre Cívic Sandaru',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '10',
  'Energia_Produeix_ kWh': '22050',
  'Nom_Districte': 'Sant Martí',
  'Emissions_ Estalviades_KgCO2': '7938',
  'Longitude': '2.184962028749',
  'Codi_Districte': '10',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '17.64',
  'Any_Alta': '2008',
  'Latitude': '41.391560512329',
  '_id': 34,
  'Adreca': 'Carrer Nàpols, 22'},
 {'Nom': 'Pèrgola Parc del Fòrum',
  'Tipus_Equipament': 'Espai públic',
  'Nombre_Llars_Subministrament': '193',
  'Energia_Produeix_ kWh': '443190',
  'Nom_Districte': 'Sant Martí',
  'Emissions_ Estalviades_KgCO2': '159548',
  'Longitude': '2.228224661299',
  'Codi_Districte': '10',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '443.19',
  'Any_Alta': '2008',
  'Latitude': '41.411564408203',
  '_id': 35,
  'Adreca': 'Parc del Fòrum'},
 {'Nom': 'Biblioteca Joan Miró',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '4',
  'Energia_Produeix_ kWh': '8250',
  'Nom_Districte': 'Eixample',
  'Emissions_ Estalviades_KgCO2': '2970',
  'Longitude': '2.149261840382',
  'Codi_Districte': '2',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '6.6',
  'Any_Alta': '2009',
  'Latitude': '41.378680340064',
  '_id': 36,
  'Adreca': 'Carrer de Vilamarí, 61'},
 {'Nom': 'La Fàbrica del Sol. Façana',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '2',
  'Energia_Produeix_ kWh': '5200',
  'Nom_Districte': 'Ciutat Vella',
  'Emissions_ Estalviades_KgCO2': '1872',
  'Longitude': '2.191846926892',
  'Codi_Districte': '1',
  'Autoconsum_Xarxa': 'Autoconsum',
  'Potencia_kWp': '5.2',
  'Any_Alta': '2010',
  'Latitude': '41.382384579589',
  '_id': 37,
  'Adreca': 'Passeig de Salvat Papasseit, 1'},
 {'Nom': 'CEIP Gaudí',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '13',
  'Energia_Produeix_ kWh': '30375',
  'Nom_Districte': 'Nou Barris',
  'Emissions_ Estalviades_KgCO2': '10935',
  'Longitude': '2.171286898058',
  'Codi_Districte': '8',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '24.3',
  'Any_Alta': '2010',
  'Latitude': '41.446744788201',
  '_id': 38,
  'Adreca': 'Carrer Artesania, 81-83'},
 {'Nom': 'Escola Bressol Galatea',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '10',
  'Energia_Produeix_ kWh': '23400',
  'Nom_Districte': 'Gràcia',
  'Emissions_ Estalviades_KgCO2': '8424',
  'Longitude': '2.140669811547',
  'Codi_Districte': '6',
  'Autoconsum_Xarxa': 'Autoconsum',
  'Potencia_kWp': '23.4',
  'Any_Alta': '2011',
  'Latitude': '41.419415751237',
  '_id': 39,
  'Adreca': 'Avinguda de Vallcarca, 229'},
 {'Nom': 'El Jardinet del Pedró/ Mitgera Teatre del Raval',
  'Tipus_Equipament': 'Parets i mitgeres',
  'Nombre_Llars_Subministrament': '0',
  'Energia_Produeix_ kWh': '500',
  'Nom_Districte': 'Ciutat Vella',
  'Emissions_ Estalviades_KgCO2': '180',
  'Longitude': '2.164954296199',
  'Codi_Districte': '1',
  'Autoconsum_Xarxa': 'Autoconsum amb bateries',
  'Potencia_kWp': '0.5',
  'Any_Alta': '2013',
  'Latitude': '41.379502387345',
  '_id': 40,
  'Adreca': 'Carrer de Sant Antoni Abat, 12'},
 {'Nom': 'Centre de Serveis Socials Raval Sud',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '10',
  'Energia_Produeix_ kWh': '22200',
  'Nom_Districte': 'Ciutat Vella',
  'Emissions_ Estalviades_KgCO2': '7992',
  'Longitude': '2.166528611546',
  'Codi_Districte': '1',
  'Autoconsum_Xarxa': 'Autoconsum',
  'Potencia_kWp': '17.76',
  'Any_Alta': '2013',
  'Latitude': '41.380033836210',
  '_id': 41,
  'Adreca': 'Carrer Carme, 101-109'},
 {'Nom': 'Palau Alòs',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '17',
  'Energia_Produeix_ kWh': '39375',
  'Nom_Districte': 'Ciutat Vella',
  'Emissions_ Estalviades_KgCO2': '14175',
  'Longitude': '2.178473240383',
  'Codi_Districte': '1',
  'Autoconsum_Xarxa': 'Connexió a xarxa',
  'Potencia_kWp': '31.5',
  'Any_Alta': '2013',
  'Latitude': '41.388377212454',
  '_id': 42,
  'Adreca': 'Carrer Sant Pere més baix, 55'},
 {'Nom': 'Seu del districte de Gràcia',
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '2',
  'Energia_Produeix_ kWh': '3750',
  'Nom_Districte': 'Gràcia',
  'Emissions_ Estalviades_KgCO2': '1350',
  'Longitude': '2.158326299913',
  'Codi_Districte': '6',
  'Autoconsum_Xarxa': 'Autoconsum',
  'Potencia_kWp': '3',
  'Any_Alta': '2013',
  'Latitude': '41.400064274839',
  '_id': 43,
  'Adreca': 'Carrer Francesc Giner, 51'},
 {'Nom': "Seu del districte d'Horta-Guinardó",
  'Tipus_Equipament': 'Coberta',
  'Nombre_Llars_Subministrament': '9',

<div style="text-align:center;">
  <h4 style="color:#F7FF56;">datastore_search:</h4>
</div>

<div style="color:#777777; font-family:monospace; width:50%; margin:0 auto; text-align:left;">
  <p>
    The <strong>datastore_search</strong> endpoint is used to <strong>query and retrieve records</strong> stored inside a dataset’s datastore.<br><br>
    It allows filtering, searching, and returning structured data such as tables, rows, or fields.<br><br>
    Common features:
  </p>

  <ul>
    <li>Search by text or keywords</li>
    <li>Filter by specific fields</li>
    <li>Limit and offset results</li>
    <li>Return data in JSON format</li>
  </ul>
</div>

<div style="text-align:center;">
  <hr style="border:0; height:2px; background-color:#777777; width:50%; margin:25px auto; box-shadow:0 2px 6px rgba(0,0,0,0.25);">
</div>

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 4 :</h4>

<p style="color:#777777;">
Convert the results into a pandas DataFrame.

In [266]:
# Dataframe

pd.set_option("display.max_rows", 20)
pd.set_option("styler.render.max_rows", 20)

df = pd.DataFrame(records)
df = df.set_index("_id")

df

,Nom,Tipus_Equipament,Nombre_Llars_Subministrament,Energia_Produeix_ kWh,Nom_Districte,Emissions_ Estalviades_KgCO2,Longitude,Codi_Districte,Autoconsum_Xarxa,Potencia_kWp,Any_Alta,Latitude,Adreca
_id,,,,,,,,,,,,,
1,Edifici Nou i Novíssim,Coberta,46,105800,Ciutat Vella,38088,2.177636994021850,1,Connexió a xarxa,84.64,2000,41.3817393706,"Plaça Sant Miquel, 1"
2,CEIP Costa i Llobera,Coberta,3,6000,Sarrià-Sant Gervasi,2160,2.108931198056360,5,Connexió a xarxa,4.8,2002,41.402116173325400,"Carrer de la Capella de Can Caralleu, 3"
3,CEIP Tàber,Coberta,16,37606,Sarrià-Sant Gervasi,13538,2.112299569219710,5,Connexió a xarxa,30.08,2002,41.401224466632500,"Carrer Esports, 9"
4,CEIP Font d'en Fargas,Coberta,3,6000,Horta-Guinardó,2160,2.165784055730250,7,Connexió a xarxa,4.8,2002,41.422796879358100,"Passeig Font d'en Fargues, 65"
5,Pèrgola de Vallbona,Espai públic,38,86400,Nou Barris,31104,2.186297977432090,8,Connexió a xarxa,86.4,2002,41.465160742776000,Carrer Castelladral 6-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,Escola La Maquinista,Coberta,13,30938,Sant Andreu,11138,2.1980623108658777,9,Autoconsum,24.75,2024,41.44649753888915,"Carrer de Ferran Junoy, 14"
208,Escola Can Fabra,Coberta,10,23625,Sant Andreu,8505,2.1915982108653496,9,Autoconsum,18.90,2024,41.43384090037771,"Carrer de Sant Adrià, 20"
209,Escola La Mar Bella,Coberta,14,31200,Sant Martí,11232,2.2045162820277744,10,Autoconsum,24.96,2024,41.400091275469926,"Plaça de Sant Bernat Calbó, 2"
210,Cotxeres TMB Horta,Coberta,245,563750,Horta-Guinardó,202950,2.1535701703914714,7,Autoconsum,451.00,2024,41.44000764401415,"Camí de Cal Notari, 110"
211,Sant Jordi Club,Coberta,268,616000,Sants-Montjuïc,221760,2.1545544127158514,3,Autoconsum,492.80,2025,41.36191565940808,"Passeig Olímpic, 6"

<hr style="
    border: 0;
    height: 2px;
    background-color:#777777;
    width:50%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">

<div style="text-align:center;">

<h4 style="color:#6F0000;">Exercise 5 :</h4>

<p style="color:#777777;">
Save the DataFrame to a file CSV.

In [267]:
# Save file

df.to_csv("plaques_fotovoltaiques.csv", index=False)

print("File created successfully!")

File created successfully!

<hr style="
    border: 0;
    height: 2px;
    background-color:#17B978;
    width:70%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
"><hr style="
    border: 0;
    height: 2px;
    background-color:#17B978;
    width:70%;
    margin:25px auto;
    box-shadow: 0 2px 6px rgba(0,0,0,0.25);
">